@echo off
echo Deploying layout.tsx to frontend...
docker exec agora-frontend-1 node -e "require('fs').mkdirSync('/app/src/app',{recursive:true});require('fs').writeFileSync('/tmp/v8_layout.tsx.b64','')"
docker exec agora-frontend-1 node -e "require('fs').appendFileSync('/tmp/v8_layout.tsx.b64','InVzZSBjbGllbnQiOwovKioKICogTkRJUCBWOCDigJQgUm9vdCBMYXlvdXQgd2l0aCBWOCBpbXByb3ZlbWVudHMKICogRUItMDA3OiB1c2VyUm9sZSBkZXJpdmVkIGZyb20gYXV0aGVudGljYXRlZCB1c2VyIHNlc3Npb24gKG5vdCBoYXJk')"
docker exec agora-frontend-1 node -e "require('fs').appendFileSync('/tmp/v8_layout.tsx.b64','Y29kZWQpCiAqIEVCLTAxMjogcGFnZURhdGEgY29udGV4dCBBUEkgZm9yIENvcGlsb3QgZGF0YSBpbmplY3Rpb24KICoKICogRHJvcCBpbnRvIC9hcHAvc3JjL2FwcC9sYXlvdXQudHN4CiAqIFJlcXVpcmVzOiBBSUNvcGlsb3QudHN4LCBI')"
docker exec agora-frontend-1 node -e "require('fs').appendFileSync('/tmp/v8_layout.tsx.b64','ZWxwT3ZlcmxheS50c3gsIEd1aWRlZFRvdXIudHN4IGluIC9jb21wb25lbnRzL3VpLwogKi8KCmltcG9ydCB0eXBlIHsgTWV0YWRhdGEgfSBmcm9tICJuZXh0IjsKaW1wb3J0ICIuL2dsb2JhbHMuY3NzIjsKaW1wb3J0ICIuL2dsb2JhbHMt')"
docker exec agora-frontend-1 node -e "require('fs').appendFileSync('/tmp/v8_layout.tsx.b64','b3ZlcnJpZGUuY3NzIjsKaW1wb3J0IFNpZGViYXIgZnJvbSAiQC9jb21wb25lbnRzL2xheW91dC9TaWRlYmFyIjsKaW1wb3J0IEFJQ29waWxvdCBmcm9tICJAL2NvbXBvbmVudHMvdWkvQUlDb3BpbG90IjsKCmV4cG9ydCBjb25zdCBtZXRh')"
docker exec agora-frontend-1 node -e "require('fs').appendFileSync('/tmp/v8_layout.tsx.b64','ZGF0YTogTWV0YWRhdGEgPSB7CiAgdGl0bGU6ICJORElQIHwgTmF0aW9uYWwgJiBEaWFzcG9yYSBJbnRlbGxpZ2VuY2UgUGxhdGZvcm0iLAogIGRlc2NyaXB0aW9uOiAiTmF0aW9uYWwgJiBEaWFzcG9yYSBJbnRlbGxpZ2VuY2UgUGxhdGZv')"
docker exec agora-frontend-1 node -e "require('fs').appendFileSync('/tmp/v8_layout.tsx.b64','cm0g4oCUIFVuZGVyc3RhbmRpbmcgTmlnZXJpYS4gVW5kZXJzdGFuZGluZyB0aGUgRGlhc3BvcmEuIEluZm9ybWluZyBMZWFkZXJzaGlwLiIsCiAgaWNvbnM6IHsgaWNvbjogIi9pY29uLnN2ZyIgfSwKfTsKCmV4cG9ydCBkZWZhdWx0IGZ1')"
docker exec agora-frontend-1 node -e "require('fs').appendFileSync('/tmp/v8_layout.tsx.b64','bmN0aW9uIFJvb3RMYXlvdXQoeyBjaGlsZHJlbiB9OiB7IGNoaWxkcmVuOiBSZWFjdC5SZWFjdE5vZGUgfSkgewogIHJldHVybiAoCiAgICA8aHRtbCBsYW5nPSJlbiI+CiAgICAgIDxib2R5IGNsYXNzTmFtZT0iZmxleCBoLXNjcmVlbiBv')"
docker exec agora-frontend-1 node -e "require('fs').appendFileSync('/tmp/v8_layout.tsx.b64','dmVyZmxvdy1oaWRkZW4iPgogICAgICAgIDxTaWRlYmFyIC8+CiAgICAgICAgPG1haW4gY2xhc3NOYW1lPSJmbGV4LTEgb3ZlcmZsb3cteS1hdXRvIGJnLXNsYXRlLTk1MCBwLTYgbGc6cC04Ij4KICAgICAgICAgIHtjaGlsZHJlbn0KICAg')"
docker exec agora-frontend-1 node -e "require('fs').appendFileSync('/tmp/v8_layout.tsx.b64','ICAgICA8L21haW4+CiAgICAgICAgey8qIEVCLTAwNzogcm9sZSBpcyByZXNvbHZlZCBmcm9tIGF1dGggdG9rZW4gaW5zaWRlIEFJQ29waWxvdCDigJQgbm8gaGFyZGNvZGVkIHJvbGUgKi99CiAgICAgICAgey8qIEVCLTAxMjogcGFnZURh')"
docker exec agora-frontend-1 node -e "require('fs').appendFileSync('/tmp/v8_layout.tsx.b64','dGEgaXMgaW5qZWN0ZWQgYnkgaW5kaXZpZHVhbCBwYWdlIGNvbXBvbmVudHMgdmlhIENvcGlsb3RQcm92aWRlciAqL30KICAgICAgICA8QUlDb3BpbG90IC8+CiAgICAgIDwvYm9keT4KICAgIDwvaHRtbD4KICApOwp9Cg==')"
docker exec agora-frontend-1 node -e "require('fs').writeFileSync('/app/src/app/layout.tsx',Buffer.from(require('fs').readFileSync('/tmp/v8_layout.tsx.b64','utf8'),'base64'));console.log('Written: /app/src/app/layout.tsx')"
echo Done: layout.tsx