@echo off
echo Deploying final fixes...

echo Deploying materialise_v8.py...
docker exec agora-backend-1 python -c "open('/tmp/ff_materialise_v8.py.b64','w').write('')"
docker exec agora-backend-1 python -c "open('/tmp/ff_materialise_v8.py.b64','a').write('IiIiCk5ESVAgVjgg4oCUIFBlcmZvcm1hbmNlIE1hdGVyaWFsaXNhdGlvbiBXb3JrZXIg4oCUIHVzZXMgOnBhcmFtIGJpbmRwYXJhbSBzdHlsZQoiIiIKaW1wb3J0IHN5cwpzeXMucGF0aC5pbnNlcnQoMCwgJy9hcHAnKQoKaW1wb3J0IGpzb24sIHRpbWUKZnJvbSBk')"
docker exec agora-backend-1 python -c "open('/tmp/ff_materialise_v8.py.b64','a').write('YXRldGltZSBpbXBvcnQgZGF0ZXRpbWUsIHRpbWV6b25lCmZyb20gc3FsYWxjaGVteSBpbXBvcnQgdGV4dApmcm9tIGFwcC5kYi5kYXRhYmFzZSBpbXBvcnQgU2Vzc2lvbkxvY2FsCgoKZGVmIHJ1bl9tYXRlcmlhbGlzYXRpb24oKToKICAgIHByaW50KCJcbiIgKyAi')"
docker exec agora-backend-1 python -c "open('/tmp/ff_materialise_v8.py.b64','a').write('PSIgKiA2MCkKICAgIHByaW50KCJORElQIFY4IOKAlCBJbnRlbGxpZ2VuY2UgTWF0ZXJpYWxpc2F0aW9uIFBpcGVsaW5lIikKICAgIHByaW50KCI9IiAqIDYwKQogICAgZGIgPSBTZXNzaW9uTG9jYWwoKQogICAgc3RhcnQgPSB0aW1lLnRpbWUoKQogICAgdHJ5Ogog')"
docker exec agora-backend-1 python -c "open('/tmp/ff_materialise_v8.py.b64','a').write('ICAgICAgIF9lbnN1cmVfbWF0ZXJpYWxpc2VkX3RhYmxlKGRiKQogICAgICAgIF9tYXRlcmlhbGlzZV9uYXJyYXRpdmVfc3VtbWFyeShkYikKICAgICAgICBfbWF0ZXJpYWxpc2VfbWV0cmljc19zdW1tYXJ5KGRiKQogICAgICAgIF9tYXRlcmlhbGlzZV9vcHBvcnR1')"
docker exec agora-backend-1 python -c "open('/tmp/ff_materialise_v8.py.b64','a').write('bml0eV9zdW1tYXJ5KGRiKQogICAgICAgIHByaW50KGYiXG4gT0sgTWF0ZXJpYWxpc2F0aW9uIGNvbXBsZXRlIGluIHtyb3VuZCh0aW1lLnRpbWUoKS1zdGFydCwxKX1zIikKICAgIGV4Y2VwdCBFeGNlcHRpb24gYXMgZToKICAgICAgICBwcmludChmIlxuIEZBSUwg')"
docker exec agora-backend-1 python -c "open('/tmp/ff_materialise_v8.py.b64','a').write('TWF0ZXJpYWxpc2F0aW9uIGZhaWxlZDoge2V9IikKICAgIGZpbmFsbHk6CiAgICAgICAgZGIuY2xvc2UoKQoKCmRlZiBfdXBzZXJ0KGRiLCBpdHlwZSwgZGF0YSk6CiAgICBkYi5leGVjdXRlKHRleHQoCiAgICAgICAgIklOU0VSVCBJTlRPIG1hdGVyaWFsaXNlZF9p')"
docker exec agora-backend-1 python -c "open('/tmp/ff_materialise_v8.py.b64','a').write('bnRlbGxpZ2VuY2UgKGludGVsbGlnZW5jZV90eXBlLCBkYXRhLCBjb21wdXRlZF9hdCwgZXhwaXJlc19hdCkgIgogICAgICAgICJWQUxVRVMgKDp0LCBjYXN0KDpkIGFzIGpzb25iKSwgTk9XKCksIE5PVygpICsgSU5URVJWQUwgJzI2IGhvdXJzJykgIgogICAgICAg')"
docker exec agora-backend-1 python -c "open('/tmp/ff_materialise_v8.py.b64','a').write('ICJPTiBDT05GTElDVCAoaW50ZWxsaWdlbmNlX3R5cGUpIERPIFVQREFURSBTRVQgZGF0YT1jYXN0KGV4Y2x1ZGVkLmRhdGEgYXMganNvbmIpLCBjb21wdXRlZF9hdD1OT1coKSwgZXhwaXJlc19hdD1OT1coKSArIElOVEVSVkFMICcyNiBob3VycyciCiAgICApLCB7')"
docker exec agora-backend-1 python -c "open('/tmp/ff_materialise_v8.py.b64','a').write('InQiOiBpdHlwZSwgImQiOiBqc29uLmR1bXBzKGRhdGEpfSkKICAgIGRiLmNvbW1pdCgpCgoKZGVmIF9lbnN1cmVfbWF0ZXJpYWxpc2VkX3RhYmxlKGRiKToKICAgIHRyeToKICAgICAgICBkYi5leGVjdXRlKHRleHQoCiAgICAgICAgICAgICJDUkVBVEUgVEFCTEUg')"
docker exec agora-backend-1 python -c "open('/tmp/ff_materialise_v8.py.b64','a').write('SUYgTk9UIEVYSVNUUyBtYXRlcmlhbGlzZWRfaW50ZWxsaWdlbmNlICgiCiAgICAgICAgICAgICJpbnRlbGxpZ2VuY2VfdHlwZSBWQVJDSEFSKDEwMCkgUFJJTUFSWSBLRVksIGRhdGEgSlNPTkIgTk9UIE5VTEwsICIKICAgICAgICAgICAgImNvbXB1dGVkX2F0IFRJ')"
docker exec agora-backend-1 python -c "open('/tmp/ff_materialise_v8.py.b64','a').write('TUVTVEFNUFRaIERFRkFVTFQgTk9XKCksIGV4cGlyZXNfYXQgVElNRVNUQU1QVFopIgogICAgICAgICkpCiAgICAgICAgZGIuY29tbWl0KCkKICAgIGV4Y2VwdCBFeGNlcHRpb246CiAgICAgICAgZGIucm9sbGJhY2soKQoKCmRlZiBfbWF0ZXJpYWxpc2VfbmFycmF0')"
docker exec agora-backend-1 python -c "open('/tmp/ff_materialise_v8.py.b64','a').write('aXZlX3N1bW1hcnkoZGIpOgogICAgcHJpbnQoIlxuWzEvM10gTWF0ZXJpYWxpc2luZyBuYXJyYXRpdmUgc3VtbWFyeS4uLiIpCiAgICB0cnk6CiAgICAgICAgcm93cyA9IGRiLmV4ZWN1dGUodGV4dCgKICAgICAgICAgICAgIlNFTEVDVCBuYXJyYXRpdmUsIFNVTSht')"
docker exec agora-backend-1 python -c "open('/tmp/ff_materialise_v8.py.b64','a').write('ZW50aW9uX2NvdW50KSBhcyB0bSwgQVZHKHNlbnRpbWVudF9hdmcpIGFzIHNhLCBBVkcodmVsb2NpdHkpIGFzIGF2ICIKICAgICAgICAgICAgIkZST00gbmFycmF0aXZlX3RyZW5kcyBXSEVSRSBkYXRlX2J1Y2tldCA+IE5PVygpIC0gSU5URVJWQUwgJzQ4IGhvdXJz')"
docker exec agora-backend-1 python -c "open('/tmp/ff_materialise_v8.py.b64','a').write('JyAiCiAgICAgICAgICAgICJHUk9VUCBCWSBuYXJyYXRpdmUgT1JERVIgQlkgdG0gREVTQyBMSU1JVCAxMSIKICAgICAgICApKS5mZXRjaGFsbCgpCiAgICAgICAgbmFycmF0aXZlcyA9IFt7Im5hcnJhdGl2ZSI6IHIubmFycmF0aXZlLCAibWVudGlvbl9jb3VudCI6')"
docker exec agora-backend-1 python -c "open('/tmp/ff_materialise_v8.py.b64','a').write('IGludChyLnRtIG9yIDApLAogICAgICAgICAgICAic2VudGltZW50X3Njb3JlIjogcm91bmQoZmxvYXQoci5zYSBvciAwKSwgMyksICJ2ZWxvY2l0eSI6IHJvdW5kKGZsb2F0KHIuYXYgb3IgMCksIDIpLAogICAgICAgICAgICAic2VudGltZW50X2xhYmVsIjogInBv')"
docker exec agora-backend-1 python -c "open('/tmp/ff_materialise_v8.py.b64','a').write('c2l0aXZlIiBpZiBmbG9hdChyLnNhIG9yIDApID4gMC4xIGVsc2UgKCJuZWdhdGl2ZSIgaWYgZmxvYXQoci5zYSBvciAwKSA8IC0wLjEgZWxzZSAibmV1dHJhbCIpfQogICAgICAgICAgICBmb3IgciBpbiByb3dzXQogICAgICAgIF91cHNlcnQoZGIsICJuYXJyYXRp')"
docker exec agora-backend-1 python -c "open('/tmp/ff_materialise_v8.py.b64','a').write('dmVfc3VtbWFyeSIsIHsibmFycmF0aXZlcyI6IG5hcnJhdGl2ZXMsICJjb21wdXRlZF9hdCI6IGRhdGV0aW1lLm5vdyh0aW1lem9uZS51dGMpLmlzb2Zvcm1hdCgpfSkKICAgICAgICBwcmludChmIiAgT0sge2xlbihuYXJyYXRpdmVzKX0gbmFycmF0aXZlcyBtYXRl')"
docker exec agora-backend-1 python -c "open('/tmp/ff_materialise_v8.py.b64','a').write('cmlhbGlzZWQiKQogICAgZXhjZXB0IEV4Y2VwdGlvbiBhcyBlOgogICAgICAgIGRiLnJvbGxiYWNrKCkKICAgICAgICBwcmludChmIiAgV0FSTiBOYXJyYXRpdmUgZmFpbGVkOiB7ZX0iKQoKCmRlZiBfbWF0ZXJpYWxpc2VfbWV0cmljc19zdW1tYXJ5KGRiKToKICAg')"
docker exec agora-backend-1 python -c "open('/tmp/ff_materialise_v8.py.b64','a').write('IHByaW50KCJcblsyLzNdIE1hdGVyaWFsaXNpbmcgbWV0cmljcyBzdW1tYXJ5Li4uIikKICAgIHRyeToKICAgICAgICByb3cgPSBkYi5leGVjdXRlKHRleHQoCiAgICAgICAgICAgICJTRUxFQ1QgZW5nYWdlbWVudF9pbmRleCwgc2VudGltZW50X3Njb3JlLCB0b3Rh')"
docker exec agora-backend-1 python -c "open('/tmp/ff_materialise_v8.py.b64','a').write('bF9wYXJ0aWNpcGFudHMsIHRvdGFsX2VuZ2FnZW1lbnRzLCBncm93dGhfcmF0ZSAiCiAgICAgICAgICAgICJGUk9NIGFuYWx5dGljc19zbmFwc2hvdHMgT1JERVIgQlkgc25hcHNob3RfZGF0ZSBERVNDIExJTUlUIDEiCiAgICAgICAgKSkuZmV0Y2hvbmUoKQogICAg')"
docker exec agora-backend-1 python -c "open('/tmp/ff_materialise_v8.py.b64','a').write('ICAgIGlmIG5vdCByb3c6CiAgICAgICAgICAgIHByaW50KCIgIFdBUk4gTm8gYW5hbHl0aWNzIHNuYXBzaG90cyBmb3VuZCIpOyByZXR1cm4KICAgICAgICBzYyA9IGRiLmV4ZWN1dGUodGV4dCgKICAgICAgICAgICAgIlNFTEVDVCBDT1VOVChESVNUSU5DVCBwbGF0')"
docker exec agora-backend-1 python -c "open('/tmp/ff_materialise_v8.py.b64','a').write('Zm9ybTo6dGV4dCkgRlJPTSBzb2NpYWxfcG9zdHMgV0hFUkUgZmV0Y2hlZF9hdCA+IE5PVygpIC0gSU5URVJWQUwgJzQ4IGhvdXJzJyIKICAgICAgICApKS5zY2FsYXIoKSBvciAwCiAgICAgICAgY29uZmlkZW5jZSA9ICJIaWdoIiBpZiBzYyA+PSA0IGVsc2UgKCJN')"
docker exec agora-backend-1 python -c "open('/tmp/ff_materialise_v8.py.b64','a').write('ZWRpdW0iIGlmIHNjID49IDIgZWxzZSAiTG93IikKICAgICAgICBkYXRhID0geyJlbmdhZ2VtZW50X2luZGV4IjogZmxvYXQocm93LmVuZ2FnZW1lbnRfaW5kZXggb3IgMCksCiAgICAgICAgICAgICAgICAic2VudGltZW50X3Njb3JlIjogZmxvYXQocm93LnNlbnRp')"
docker exec agora-backend-1 python -c "open('/tmp/ff_materialise_v8.py.b64','a').write('bWVudF9zY29yZSBvciAwKSwKICAgICAgICAgICAgICAgICJ0b3RhbF9wYXJ0aWNpcGFudHMiOiBpbnQocm93LnRvdGFsX3BhcnRpY2lwYW50cyBvciAwKSwKICAgICAgICAgICAgICAgICJ0b3RhbF9lbmdhZ2VtZW50cyI6IGludChyb3cudG90YWxfZW5nYWdlbWVu')"
docker exec agora-backend-1 python -c "open('/tmp/ff_materialise_v8.py.b64','a').write('dHMgb3IgMCksCiAgICAgICAgICAgICAgICAiZ3Jvd3RoX3JhdGUiOiBmbG9hdChyb3cuZ3Jvd3RoX3JhdGUgb3IgMCksCiAgICAgICAgICAgICAgICAiYWN0aXZlX3NvdXJjZXMiOiBpbnQoc2MpLCAiY29uZmlkZW5jZV9sYWJlbCI6IGNvbmZpZGVuY2UsCiAgICAg')"
docker exec agora-backend-1 python -c "open('/tmp/ff_materialise_v8.py.b64','a').write('ICAgICAgICAgICAiY29tcHV0ZWRfYXQiOiBkYXRldGltZS5ub3codGltZXpvbmUudXRjKS5pc29mb3JtYXQoKX0KICAgICAgICBfdXBzZXJ0KGRiLCAibWV0cmljc19zdW1tYXJ5IiwgZGF0YSkKICAgICAgICBwcmludChmIiAgT0sgRW5nYWdlbWVudCBJbmRleDog')"
docker exec agora-backend-1 python -c "open('/tmp/ff_materialise_v8.py.b64','a').write('e2RhdGFbJ2VuZ2FnZW1lbnRfaW5kZXgnXX0sIENvbmZpZGVuY2U6IHtjb25maWRlbmNlfSIpCiAgICBleGNlcHQgRXhjZXB0aW9uIGFzIGU6CiAgICAgICAgZGIucm9sbGJhY2soKQogICAgICAgIHByaW50KGYiICBXQVJOIE1ldHJpY3MgZmFpbGVkOiB7ZX0iKQoK')"
docker exec agora-backend-1 python -c "open('/tmp/ff_materialise_v8.py.b64','a').write('CmRlZiBfbWF0ZXJpYWxpc2Vfb3Bwb3J0dW5pdHlfc3VtbWFyeShkYik6CiAgICBwcmludCgiXG5bMy8zXSBNYXRlcmlhbGlzaW5nIG9wcG9ydHVuaXR5IHN1bW1hcnkuLi4iKQogICAgdHJ5OgogICAgICAgIHJvd3MgPSBkYi5leGVjdXRlKHRleHQoCiAgICAgICAg')"
docker exec agora-backend-1 python -c "open('/tmp/ff_materialise_v8.py.b64','a').write('ICAgICJTRUxFQ1QgdGl0bGUsIGNvbmZpZGVuY2UsIHByb2JhYmlsaXR5X29mX3N1Y2Nlc3MsIHN0YXR1cywgY2F0ZWdvcnksICIKICAgICAgICAgICAgIndoYXRfb3Bwb3J0dW5pdHlfZXhpc3RzLCBldmlkZW5jZV9wb3N0X2NvdW50IEZST00gb3Bwb3J0dW5pdHlf')"
docker exec agora-backend-1 python -c "open('/tmp/ff_materialise_v8.py.b64','a').write('YXNzZXNzbWVudHMgIgogICAgICAgICAgICAiT1JERVIgQlkgcHJvYmFiaWxpdHlfb2Zfc3VjY2VzcyBERVNDIE5VTExTIExBU1QgTElNSVQgMTAiCiAgICAgICAgKSkuZmV0Y2hhbGwoKQogICAgICAgIG9wcHMgPSBbeyJ0aXRsZSI6IHIudGl0bGUsICJjb25maWRl')"
docker exec agora-backend-1 python -c "open('/tmp/ff_materialise_v8.py.b64','a').write('bmNlIjogci5jb25maWRlbmNlLAogICAgICAgICAgICAgICAgICJwcm9iYWJpbGl0eSI6IGZsb2F0KHIucHJvYmFiaWxpdHlfb2Zfc3VjY2VzcyBvciAwKSwgInN0YXR1cyI6IHIuc3RhdHVzLAogICAgICAgICAgICAgICAgICJjYXRlZ29yeSI6IHIuY2F0ZWdvcnks')"
docker exec agora-backend-1 python -c "open('/tmp/ff_materialise_v8.py.b64','a').write('ICJkZXNjcmlwdGlvbiI6IChyLndoYXRfb3Bwb3J0dW5pdHlfZXhpc3RzIG9yICIiKVs6MjAwXSwKICAgICAgICAgICAgICAgICAiZXZpZGVuY2VfcG9zdHMiOiByLmV2aWRlbmNlX3Bvc3RfY291bnQgb3IgMH0gZm9yIHIgaW4gcm93c10KICAgICAgICBfdXBzZXJ0')"
docker exec agora-backend-1 python -c "open('/tmp/ff_materialise_v8.py.b64','a').write('KGRiLCAib3Bwb3J0dW5pdHlfc3VtbWFyeSIsIHsib3Bwb3J0dW5pdGllcyI6IG9wcHMsICJjb21wdXRlZF9hdCI6IGRhdGV0aW1lLm5vdyh0aW1lem9uZS51dGMpLmlzb2Zvcm1hdCgpfSkKICAgICAgICBwcmludChmIiAgT0sge2xlbihvcHBzKX0gb3Bwb3J0dW5p')"
docker exec agora-backend-1 python -c "open('/tmp/ff_materialise_v8.py.b64','a').write('dGllcyBtYXRlcmlhbGlzZWQiKQogICAgZXhjZXB0IEV4Y2VwdGlvbiBhcyBlOgogICAgICAgIGRiLnJvbGxiYWNrKCkKICAgICAgICBwcmludChmIiAgV0FSTiBPcHBvcnR1bml0aWVzIGZhaWxlZDoge2V9IikKCgppZiBfX25hbWVfXyA9PSAiX19tYWluX18iOgog')"
docker exec agora-backend-1 python -c "open('/tmp/ff_materialise_v8.py.b64','a').write('ICAgcnVuX21hdGVyaWFsaXNhdGlvbigpCg==')"
docker exec agora-backend-1 python -c "import base64;open('/app/scripts/materialise_v8.py','wb').write(base64.b64decode(open('/tmp/ff_materialise_v8.py.b64').read()));print('Written: /app/scripts/materialise_v8.py')"

echo Deploying daily_snapshot.py...
docker exec agora-backend-1 python -c "open('/tmp/ff_daily_snapshot.py.b64','w').write('')"
docker exec agora-backend-1 python -c "open('/tmp/ff_daily_snapshot.py.b64','a').write('IiIiCk5ESVAgVjgg4oCUIERhaWx5IEludGVsbGlnZW5jZSBTbmFwc2hvdCBXb3JrZXIg4oCUIHVzZXMgOnBhcmFtIGJpbmRwYXJhbSBzdHlsZQoiIiIKaW1wb3J0IHN5cwpzeXMucGF0aC5pbnNlcnQoMCwgJy9hcHAnKQoKaW1wb3J0IGpzb24KZnJvbSBkYXRldGlt')"
docker exec agora-backend-1 python -c "open('/tmp/ff_daily_snapshot.py.b64','a').write('ZSBpbXBvcnQgZGF0ZXRpbWUsIHRpbWV6b25lLCBkYXRlLCB0aW1lZGVsdGEKZnJvbSBzcWxhbGNoZW15IGltcG9ydCB0ZXh0CmZyb20gYXBwLmRiLmRhdGFiYXNlIGltcG9ydCBTZXNzaW9uTG9jYWwKCgpkZWYgdGFrZV9zbmFwc2hvdChkYik6CiAgICB0b2RheSA9')"
docker exec agora-backend-1 python -c "open('/tmp/ff_daily_snapshot.py.b64','a').write('IGRhdGUudG9kYXkoKQogICAgcHJpbnQoZiJUYWtpbmcgc25hcHNob3QgZm9yIHt0b2RheX0uLi4iKQoKICAgICMgTmFycmF0aXZlcwogICAgbmFycmF0aXZlX2RhdGEgPSBbXQogICAgdHJ5OgogICAgICAgIHJvd3MgPSBkYi5leGVjdXRlKHRleHQoCiAgICAgICAg')"
docker exec agora-backend-1 python -c "open('/tmp/ff_daily_snapshot.py.b64','a').write('ICAgICJTRUxFQ1QgbmFycmF0aXZlLCBTVU0obWVudGlvbl9jb3VudCkgYXMgdG0sIEFWRyhzZW50aW1lbnRfYXZnKSBhcyBzYSwgQVZHKHZlbG9jaXR5KSBhcyBhdiAiCiAgICAgICAgICAgICJGUk9NIG5hcnJhdGl2ZV90cmVuZHMgV0hFUkUgZGF0ZV9idWNrZXQg')"
docker exec agora-backend-1 python -c "open('/tmp/ff_daily_snapshot.py.b64','a').write('PiBOT1coKSAtIElOVEVSVkFMICc0OCBob3VycycgIgogICAgICAgICAgICAiR1JPVVAgQlkgbmFycmF0aXZlIE9SREVSIEJZIHRtIERFU0MgTElNSVQgMTEiCiAgICAgICAgKSkuZmV0Y2hhbGwoKQogICAgICAgIG5hcnJhdGl2ZV9kYXRhID0gW3sibmFycmF0aXZl')"
docker exec agora-backend-1 python -c "open('/tmp/ff_daily_snapshot.py.b64','a').write('Ijogci5uYXJyYXRpdmUsICJtZW50aW9uX2NvdW50IjogaW50KHIudG0gb3IgMCksCiAgICAgICAgICAgICJzZW50aW1lbnRfc2NvcmUiOiByb3VuZChmbG9hdChyLnNhIG9yIDApLCAzKSwgInZlbG9jaXR5Ijogcm91bmQoZmxvYXQoci5hdiBvciAwKSwgMil9CiAg')"
docker exec agora-backend-1 python -c "open('/tmp/ff_daily_snapshot.py.b64','a').write('ICAgICAgICAgIGZvciByIGluIHJvd3NdCiAgICAgICAgcHJpbnQoZiIgIE9LIE5hcnJhdGl2ZXM6IHtsZW4obmFycmF0aXZlX2RhdGEpfSIpCiAgICBleGNlcHQgRXhjZXB0aW9uIGFzIGU6CiAgICAgICAgZGIucm9sbGJhY2soKTsgcHJpbnQoZiIgIFdBUk4gbmFy')"
docker exec agora-backend-1 python -c "open('/tmp/ff_daily_snapshot.py.b64','a').write('cmF0aXZlczoge2V9IikKCiAgICAjIE1ldHJpY3MKICAgIGVuZ2FnZW1lbnRfaW5kZXggPSBzZW50aW1lbnRfc2NvcmUgPSBOb25lCiAgICB0cnk6CiAgICAgICAgcm93ID0gZGIuZXhlY3V0ZSh0ZXh0KAogICAgICAgICAgICAiU0VMRUNUIGVuZ2FnZW1lbnRfaW5k')"
docker exec agora-backend-1 python -c "open('/tmp/ff_daily_snapshot.py.b64','a').write('ZXgsIHNlbnRpbWVudF9zY29yZSBGUk9NIGFuYWx5dGljc19zbmFwc2hvdHMgT1JERVIgQlkgc25hcHNob3RfZGF0ZSBERVNDIExJTUlUIDEiCiAgICAgICAgKSkuZmV0Y2hvbmUoKQogICAgICAgIGlmIHJvdzoKICAgICAgICAgICAgZW5nYWdlbWVudF9pbmRleCA9')"
docker exec agora-backend-1 python -c "open('/tmp/ff_daily_snapshot.py.b64','a').write('IGZsb2F0KHJvdy5lbmdhZ2VtZW50X2luZGV4IG9yIDApCiAgICAgICAgICAgIHNlbnRpbWVudF9zY29yZSA9IGZsb2F0KHJvdy5zZW50aW1lbnRfc2NvcmUgb3IgMCkKICAgICAgICBwcmludChmIiAgT0sgRW5nYWdlbWVudDoge2VuZ2FnZW1lbnRfaW5kZXh9LCBT')"
docker exec agora-backend-1 python -c "open('/tmp/ff_daily_snapshot.py.b64','a').write('ZW50aW1lbnQ6IHtzZW50aW1lbnRfc2NvcmV9IikKICAgIGV4Y2VwdCBFeGNlcHRpb24gYXMgZToKICAgICAgICBkYi5yb2xsYmFjaygpOyBwcmludChmIiAgV0FSTiBtZXRyaWNzOiB7ZX0iKQoKICAgICMgU3Rha2Vob2xkZXJzCiAgICB0b3Bfc3Rha2Vob2xkZXJz')"
docker exec agora-backend-1 python -c "open('/tmp/ff_daily_snapshot.py.b64','a').write('ID0gW10KICAgIHRyeToKICAgICAgICByb3dzID0gZGIuZXhlY3V0ZSh0ZXh0KAogICAgICAgICAgICAiU0VMRUNUIHNpcC5zdGFrZWhvbGRlcl9pZCwgc3IubmFtZSwgc2lwLmNvbXBvc2l0ZV9pbmRleCwgc2lwLmluZmx1ZW5jZV9sZXZlbCAiCiAgICAgICAgICAg')"
docker exec agora-backend-1 python -c "open('/tmp/ff_daily_snapshot.py.b64','a').write('ICJGUk9NIHN0YWtlaG9sZGVyX2luZmx1ZW5jZV9wcm9maWxlcyBzaXAgIgogICAgICAgICAgICAiSk9JTiBzdGFrZWhvbGRlcl9yZWdpc3RyeSBzciBPTiBzci5pZCA9IHNpcC5zdGFrZWhvbGRlcl9pZCAiCiAgICAgICAgICAgICJPUkRFUiBCWSBzaXAuY29tcG9z')"
docker exec agora-backend-1 python -c "open('/tmp/ff_daily_snapshot.py.b64','a').write('aXRlX2luZGV4IERFU0MgTElNSVQgMTAiCiAgICAgICAgKSkuZmV0Y2hhbGwoKQogICAgICAgIHRvcF9zdGFrZWhvbGRlcnMgPSBbeyJpZCI6IHIuc3Rha2Vob2xkZXJfaWQsICJuYW1lIjogci5uYW1lLAogICAgICAgICAgICAiY29tcG9zaXRlX2luZGV4IjogZmxv')"
docker exec agora-backend-1 python -c "open('/tmp/ff_daily_snapshot.py.b64','a').write('YXQoci5jb21wb3NpdGVfaW5kZXggb3IgMCksICJsZXZlbCI6IHIuaW5mbHVlbmNlX2xldmVsfQogICAgICAgICAgICBmb3IgciBpbiByb3dzXQogICAgICAgIHByaW50KGYiICBPSyBTdGFrZWhvbGRlcnM6IHtsZW4odG9wX3N0YWtlaG9sZGVycyl9IikKICAgIGV4')"
docker exec agora-backend-1 python -c "open('/tmp/ff_daily_snapshot.py.b64','a').write('Y2VwdCBFeGNlcHRpb24gYXMgZToKICAgICAgICBkYi5yb2xsYmFjaygpOyBwcmludChmIiAgV0FSTiBzdGFrZWhvbGRlcnM6IHtlfSIpCgogICAgIyBPcHBvcnR1bml0aWVzCiAgICB0b3Bfb3Bwb3J0dW5pdGllcyA9IFtdCiAgICB0cnk6CiAgICAgICAgcm93cyA9')"
docker exec agora-backend-1 python -c "open('/tmp/ff_daily_snapshot.py.b64','a').write('IGRiLmV4ZWN1dGUodGV4dCgKICAgICAgICAgICAgIlNFTEVDVCB0aXRsZSwgY29uZmlkZW5jZSwgcHJvYmFiaWxpdHlfb2Zfc3VjY2Vzcywgc3RhdHVzICIKICAgICAgICAgICAgIkZST00gb3Bwb3J0dW5pdHlfYXNzZXNzbWVudHMgT1JERVIgQlkgcHJvYmFiaWxp')"
docker exec agora-backend-1 python -c "open('/tmp/ff_daily_snapshot.py.b64','a').write('dHlfb2Zfc3VjY2VzcyBERVNDIE5VTExTIExBU1QgTElNSVQgNSIKICAgICAgICApKS5mZXRjaGFsbCgpCiAgICAgICAgdG9wX29wcG9ydHVuaXRpZXMgPSBbeyJ0aXRsZSI6IHIudGl0bGUsICJjb25maWRlbmNlIjogci5jb25maWRlbmNlLAogICAgICAgICAgICAi')"
docker exec agora-backend-1 python -c "open('/tmp/ff_daily_snapshot.py.b64','a').write('cHJvYmFiaWxpdHkiOiBmbG9hdChyLnByb2JhYmlsaXR5X29mX3N1Y2Nlc3Mgb3IgMCksICJzdGF0dXMiOiByLnN0YXR1c30KICAgICAgICAgICAgZm9yIHIgaW4gcm93c10KICAgICAgICBwcmludChmIiAgT0sgT3Bwb3J0dW5pdGllczoge2xlbih0b3Bfb3Bwb3J0')"
docker exec agora-backend-1 python -c "open('/tmp/ff_daily_snapshot.py.b64','a').write('dW5pdGllcyl9IikKICAgIGV4Y2VwdCBFeGNlcHRpb24gYXMgZToKICAgICAgICBkYi5yb2xsYmFjaygpOyBwcmludChmIiAgV0FSTiBvcHBvcnR1bml0aWVzOiB7ZX0iKQoKICAgIGNvbmZpZGVuY2VfbGFiZWwgPSAiTWVkaXVtIgoKICAgICMgV3JpdGUgc25hcHNo')"
docker exec agora-backend-1 python -c "open('/tmp/ff_daily_snapshot.py.b64','a').write('b3QgdXNpbmcgOnBhcmFtIHN0eWxlIOKAlCBubyAlIGNoYXJhY3RlcnMKICAgIHRyeToKICAgICAgICBkYi5leGVjdXRlKHRleHQoCiAgICAgICAgICAgICJJTlNFUlQgSU5UTyBkYWlseV9pbnRlbGxpZ2VuY2Vfc25hcHNob3RzICgiCiAgICAgICAgICAgICJzbmFw')"
docker exec agora-backend-1 python -c "open('/tmp/ff_daily_snapshot.py.b64','a').write('c2hvdF9kYXRlLCBzbmFwc2hvdF90eXBlLCBuYXJyYXRpdmVfZGF0YSwgZW5nYWdlbWVudF9pbmRleCwgc2VudGltZW50X3Njb3JlLCAiCiAgICAgICAgICAgICJ3YXRjaGxpc3RfZGF0YSwgd2F0Y2hsaXN0X2NyaXRpY2FsX2NvdW50LCB3YXRjaGxpc3RfaGlnaF9j')"
docker exec agora-backend-1 python -c "open('/tmp/ff_daily_snapshot.py.b64','a').write('b3VudCwgIgogICAgICAgICAgICAidG9wX3N0YWtlaG9sZGVycywgdG9wX29wcG9ydHVuaXRpZXMsIGNvbmZpZGVuY2VfbGFiZWwsIGNyZWF0ZWRfYXQiCiAgICAgICAgICAgICIpIFZBTFVFUyAoIgogICAgICAgICAgICAiOnNkYXRlLCAnZGFpbHknLCBjYXN0KDpu')"
docker exec agora-backend-1 python -c "open('/tmp/ff_daily_snapshot.py.b64','a').write('ZGF0YSBhcyBqc29uYiksIDplaWR4LCA6c3Njb3JlLCAiCiAgICAgICAgICAgICJjYXN0KDp3ZGF0YSBhcyBqc29uYiksIDAsIDAsICIKICAgICAgICAgICAgImNhc3QoOnRzdGsgYXMganNvbmIpLCBjYXN0KDp0b3BwcyBhcyBqc29uYiksIDpjb25mLCBOT1coKSIK')"
docker exec agora-backend-1 python -c "open('/tmp/ff_daily_snapshot.py.b64','a').write('ICAgICAgICAgICAgIikgT04gQ09ORkxJQ1QgKHNuYXBzaG90X2RhdGUsIHNuYXBzaG90X3R5cGUpIERPIFVQREFURSBTRVQgIgogICAgICAgICAgICAibmFycmF0aXZlX2RhdGE9Y2FzdChleGNsdWRlZC5uYXJyYXRpdmVfZGF0YSBhcyBqc29uYiksICIKICAgICAg')"
docker exec agora-backend-1 python -c "open('/tmp/ff_daily_snapshot.py.b64','a').write('ICAgICAgImVuZ2FnZW1lbnRfaW5kZXg9ZXhjbHVkZWQuZW5nYWdlbWVudF9pbmRleCwgIgogICAgICAgICAgICAic2VudGltZW50X3Njb3JlPWV4Y2x1ZGVkLnNlbnRpbWVudF9zY29yZSwgIgogICAgICAgICAgICAidG9wX3N0YWtlaG9sZGVycz1jYXN0KGV4Y2x1')"
docker exec agora-backend-1 python -c "open('/tmp/ff_daily_snapshot.py.b64','a').write('ZGVkLnRvcF9zdGFrZWhvbGRlcnMgYXMganNvbmIpLCAiCiAgICAgICAgICAgICJ0b3Bfb3Bwb3J0dW5pdGllcz1jYXN0KGV4Y2x1ZGVkLnRvcF9vcHBvcnR1bml0aWVzIGFzIGpzb25iKSwgIgogICAgICAgICAgICAiY3JlYXRlZF9hdD1OT1coKSIKICAgICAgICAp')"
docker exec agora-backend-1 python -c "open('/tmp/ff_daily_snapshot.py.b64','a').write('LCB7CiAgICAgICAgICAgICJzZGF0ZSI6IHRvZGF5LAogICAgICAgICAgICAibmRhdGEiOiBqc29uLmR1bXBzKG5hcnJhdGl2ZV9kYXRhKSwKICAgICAgICAgICAgImVpZHgiOiBlbmdhZ2VtZW50X2luZGV4LAogICAgICAgICAgICAic3Njb3JlIjogc2VudGltZW50')"
docker exec agora-backend-1 python -c "open('/tmp/ff_daily_snapshot.py.b64','a').write('X3Njb3JlLAogICAgICAgICAgICAid2RhdGEiOiBqc29uLmR1bXBzKFtdKSwKICAgICAgICAgICAgInRzdGsiOiBqc29uLmR1bXBzKHRvcF9zdGFrZWhvbGRlcnMpLAogICAgICAgICAgICAidG9wcHMiOiBqc29uLmR1bXBzKHRvcF9vcHBvcnR1bml0aWVzKSwKICAg')"
docker exec agora-backend-1 python -c "open('/tmp/ff_daily_snapshot.py.b64','a').write('ICAgICAgICAgImNvbmYiOiBjb25maWRlbmNlX2xhYmVsLAogICAgICAgIH0pCiAgICAgICAgZGIuY29tbWl0KCkKICAgICAgICBwcmludChmIiAgT0sgU25hcHNob3Qgc2F2ZWQgZm9yIHt0b2RheX0iKQogICAgZXhjZXB0IEV4Y2VwdGlvbiBhcyBlOgogICAgICAg')"
docker exec agora-backend-1 python -c "open('/tmp/ff_daily_snapshot.py.b64','a').write('IGRiLnJvbGxiYWNrKCkKICAgICAgICBwcmludChmIiAgRkFJTCBTYXZlIHNuYXBzaG90OiB7ZX0iKQogICAgICAgIHJhaXNlCgoKZGVmIHJ1bigpOgogICAgcHJpbnQoIk5ESVAgVjgg4oCUIERhaWx5IEludGVsbGlnZW5jZSBTbmFwc2hvdCIpCiAgICBwcmludCgi')"
docker exec agora-backend-1 python -c "open('/tmp/ff_daily_snapshot.py.b64','a').write('PSIgKiA1MCkKICAgIGRiID0gU2Vzc2lvbkxvY2FsKCkKICAgIHRyeToKICAgICAgICB0YWtlX3NuYXBzaG90KGRiKQogICAgZmluYWxseToKICAgICAgICBkYi5jbG9zZSgpCiAgICBwcmludCgiPSIgKiA1MCkKICAgIHByaW50KCJTbmFwc2hvdCBjb21wbGV0ZS4i')"
docker exec agora-backend-1 python -c "open('/tmp/ff_daily_snapshot.py.b64','a').write('KQoKCmlmIF9fbmFtZV9fID09ICJfX21haW5fXyI6CiAgICBydW4oKQo=')"
docker exec agora-backend-1 python -c "import base64;open('/app/scripts/daily_snapshot.py','wb').write(base64.b64decode(open('/tmp/ff_daily_snapshot.py.b64').read()));print('Written: /app/scripts/daily_snapshot.py')"

echo Deploying layout.tsx via backend...
docker exec agora-backend-1 python -c "open('/tmp/ff_layout.b64','w').write('')"
docker exec agora-backend-1 python -c "open('/tmp/ff_layout.b64','a').write('aW1wb3J0IHR5cGUgeyBNZXRhZGF0YSB9IGZyb20gIm5leHQiOwppbXBvcnQgIi4vZ2xvYmFscy5jc3MiOwppbXBvcnQgIi4vZ2xvYmFscy1vdmVycmlkZS5jc3MiOwppbXBvcnQgU2lkZWJhciBmcm9tICJAL2NvbXBvbmVudHMvbGF5b3V0')"
docker exec agora-backend-1 python -c "open('/tmp/ff_layout.b64','a').write('L1NpZGViYXIiOwppbXBvcnQgQUlDb3BpbG90IGZyb20gIkAvY29tcG9uZW50cy91aS9BSUNvcGlsb3QiOwoKZXhwb3J0IGNvbnN0IG1ldGFkYXRhOiBNZXRhZGF0YSA9IHsKICB0aXRsZTogIk5ESVAgfCBOYXRpb25hbCAmIERpYXNwb3Jh')"
docker exec agora-backend-1 python -c "open('/tmp/ff_layout.b64','a').write('IEludGVsbGlnZW5jZSBQbGF0Zm9ybSIsCiAgZGVzY3JpcHRpb246ICJOYXRpb25hbCAmIERpYXNwb3JhIEludGVsbGlnZW5jZSBQbGF0Zm9ybSDigJQgVW5kZXJzdGFuZGluZyBOaWdlcmlhLiBVbmRlcnN0YW5kaW5nIHRoZSBEaWFzcG9y')"
docker exec agora-backend-1 python -c "open('/tmp/ff_layout.b64','a').write('YS4gSW5mb3JtaW5nIExlYWRlcnNoaXAuIiwKICBpY29uczogeyBpY29uOiAiL2ljb24uc3ZnIiB9LAp9OwoKZXhwb3J0IGRlZmF1bHQgZnVuY3Rpb24gUm9vdExheW91dCh7IGNoaWxkcmVuIH06IHsgY2hpbGRyZW46IFJlYWN0LlJlYWN0')"
docker exec agora-backend-1 python -c "open('/tmp/ff_layout.b64','a').write('Tm9kZSB9KSB7CiAgcmV0dXJuICgKICAgIDxodG1sIGxhbmc9ImVuIj4KICAgICAgPGJvZHkgY2xhc3NOYW1lPSJmbGV4IGgtc2NyZWVuIG92ZXJmbG93LWhpZGRlbiI+CiAgICAgICAgPFNpZGViYXIgLz4KICAgICAgICA8bWFpbiBjbGFz')"
docker exec agora-backend-1 python -c "open('/tmp/ff_layout.b64','a').write('c05hbWU9ImZsZXgtMSBvdmVyZmxvdy15LWF1dG8gYmctc2xhdGUtOTUwIHAtNiBsZzpwLTgiPgogICAgICAgICAge2NoaWxkcmVufQogICAgICAgIDwvbWFpbj4KICAgICAgICA8QUlDb3BpbG90IC8+CiAgICAgIDwvYm9keT4KICAgIDwv')"
docker exec agora-backend-1 python -c "open('/tmp/ff_layout.b64','a').write('aHRtbD4KICApOwp9Cg==')"
docker exec agora-backend-1 python -c "import base64;open('/tmp/layout.tsx','wb').write(base64.b64decode(open('/tmp/ff_layout.b64').read()));print('layout.tsx ready in backend /tmp')"
docker cp agora-backend-1:/tmp/layout.tsx agora-frontend-1:/app/src/app/layout.tsx
echo layout.tsx deployed

echo Starting frontend if not running...
docker compose up -d frontend
timeout /t 5 /nobreak >nul

echo Running corrected materialisation...
docker exec agora-backend-1 python scripts/materialise_v8.py

echo Running snapshot...
docker exec agora-backend-1 python scripts/daily_snapshot.py

echo Rebuilding frontend...
docker exec agora-frontend-1 npm run build
docker restart agora-frontend-1

echo ============================================================
echo  All fixes applied. Open http://localhost:3000
echo ============================================================
pause