@echo off
echo NDIP Phase C - Batch 4: Memory-aware Copilot
echo.
echo Step 1: Writing patch script...
docker exec agora-backend-1 python -c "open('/tmp/b4patch.b64','w').write('')"
docker exec agora-backend-1 python -c "open('/tmp/b4patch.b64','a').write('IyEvdXNyL2Jpbi9lbnYgcHl0aG9uMwoiIiIKTkRJUCBQaGFzZSBDIEJhdGNoIDQg4oCUIE1lbW9yeS1hd2FyZSBDb3BpbG90IFBhdGNoZXIKUGF0Y2hlcyBjb3BpbG90X3Y4LnB5IHRvOgogIDEuIFNlYXJjaCBvcmdhbmlzYXRpb25hbCBt')"
docker exec agora-backend-1 python -c "open('/tmp/b4patch.b64','a').write('ZW1vcnkgYmVmb3JlIGV2ZXJ5IHJlc3BvbnNlCiAgMi4gSW5qZWN0IG1lbW9yeSBjb250ZXh0IGludG8gc3lzdGVtIHByb21wdAogIDMuIEF1dG8tcmVnaXN0ZXIgcmVjb21tZW5kYXRpb25zIGZyb20gcmVzcG9uc2VzCiAgNC4gRW1pdCBD')"
docker exec agora-backend-1 python -c "open('/tmp/b4patch.b64','a').write('b3BpbG90Q29uc3VsdGVkIGV2ZW50cwoiIiIKaW1wb3J0IHN5cywgcmUKc3lzLnBhdGguaW5zZXJ0KDAsICcvYXBwJykKCnBhdGggPSAnL2FwcC9hcHAvYXBpL3JvdXRlcy9jb3BpbG90X3Y4LnB5Jwp3aXRoIG9wZW4ocGF0aCkgYXMgZjoK')"
docker exec agora-backend-1 python -c "open('/tmp/b4patch.b64','a').write('ICAgIGNvbnRlbnQgPSBmLnJlYWQoKQoKYWxyZWFkeV9wYXRjaGVkID0gJ1BIQVNFX0NfTUVNT1JZJyBpbiBjb250ZW50CmlmIGFscmVhZHlfcGF0Y2hlZDoKICAgIHByaW50KCdBbHJlYWR5IHBhdGNoZWQg4oCUIHNraXBwaW5nJykKICAg')"
docker exec agora-backend-1 python -c "open('/tmp/b4patch.b64','a').write('IHN5cy5leGl0KDApCgojIOKUgOKUgCBTdGVwIDE6IEFkZCBQaGFzZSBDIGltcG9ydHMgYWZ0ZXIgZXhpc3RpbmcgaW1wb3J0cyDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDi')"
docker exec agora-backend-1 python -c "open('/tmp/b4patch.b64','a').write('lIAKcGhhc2VfY19pbXBvcnRzID0gIiIiCiMgUEhBU0VfQ19NRU1PUlkg4oCUIEFkYXB0aXZlIExlYXJuaW5nIGludGVncmF0aW9uCnRyeToKICAgIGZyb20gYXBwLnBoYXNlX2Muc2VydmljZXMuY29waWxvdF9tZW1vcnkgaW1wb3J0IGJ1')"
docker exec agora-backend-1 python -c "open('/tmp/b4patch.b64','a').write('aWxkX21lbW9yeV9hd2FyZV9zeXN0ZW1fcHJvbXB0CiAgICBmcm9tIGFwcC5waGFzZV9jLnNlcnZpY2VzLnJlY29tbWVuZGF0aW9uX3JlZ2lzdHJ5IGltcG9ydCByZWdpc3Rlcl9yZWNvbW1lbmRhdGlvbl9mcm9tX2NvcGlsb3QKICAgIGZy')"
docker exec agora-backend-1 python -c "open('/tmp/b4patch.b64','a').write('b20gYXBwLnBoYXNlX2Muc2VydmljZXMuZXZlbnRfc2VydmljZSBpbXBvcnQgZW1pdF9jb3BpbG90X2NvbnN1bHRlZAogICAgUEhBU0VfQ19FTkFCTEVEID0gVHJ1ZQogICAgcHJpbnQoJ1tQaGFzZSBDXSBNZW1vcnktYXdhcmUgQ29waWxv')"
docker exec agora-backend-1 python -c "open('/tmp/b4patch.b64','a').write('dDogZW5hYmxlZCcpCmV4Y2VwdCBFeGNlcHRpb24gYXMgX3BjX2VycjoKICAgIFBIQVNFX0NfRU5BQkxFRCA9IEZhbHNlCiAgICBwcmludChmJ1tQaGFzZSBDXSBNZW1vcnktYXdhcmUgQ29waWxvdDogZGlzYWJsZWQgKHtfcGNfZXJyfSkn')"
docker exec agora-backend-1 python -c "open('/tmp/b4patch.b64','a').write('KQoiIiIKCiMgSW5zZXJ0IGFmdGVyIHRoZSBsYXN0IGltcG9ydCBsaW5lCmxpbmVzID0gY29udGVudC5zcGxpdCgnXG4nKQpsYXN0X2ltcG9ydCA9IDAKZm9yIGksIGxpbmUgaW4gZW51bWVyYXRlKGxpbmVzKToKICAgIGlmIGxpbmUuc3Rh')"
docker exec agora-backend-1 python -c "open('/tmp/b4patch.b64','a').write('cnRzd2l0aCgnZnJvbSAnKSBvciBsaW5lLnN0YXJ0c3dpdGgoJ2ltcG9ydCAnKToKICAgICAgICBsYXN0X2ltcG9ydCA9IGkKbGluZXMuaW5zZXJ0KGxhc3RfaW1wb3J0ICsgMSwgcGhhc2VfY19pbXBvcnRzKQpjb250ZW50ID0gJ1xuJy5q')"
docker exec agora-backend-1 python -c "open('/tmp/b4patch.b64','a').write('b2luKGxpbmVzKQoKIyDilIDilIAgU3RlcCAyOiBGaW5kIHdoZXJlIHRoZSBzeXN0ZW0gcHJvbXB0IGlzIGJ1aWx0IGFuZCBpbmplY3QgbWVtb3J5IOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgAojIExvb2sgZm9yIHBhdHRlcm5zIGxp')"
docker exec agora-backend-1 python -c "open('/tmp/b4patch.b64','a').write('a2U6IHN5c3RlbV9wcm9tcHQgPSAuLi4gb3IgInN5c3RlbSI6IC4uLgojIFRoZSBjb3BpbG90IGJ1aWxkcyBtZXNzYWdlcyBmb3IgQW50aHJvcGljIOKAlCB3ZSBuZWVkIHRvIGVucmljaCB0aGUgc3lzdGVtCgojIEZpbmQgdGhlIGFzeW5j')"
docker exec agora-backend-1 python -c "open('/tmp/b4patch.b64','a').write('IGNoYXQgZnVuY3Rpb24KY2hhdF9mbl9wYXR0ZXJucyA9IFsKICAgICdhc3luYyBkZWYgY2hhdCgnLAogICAgJ2FzeW5jIGRlZiBjb3BpbG90KCcsCiAgICAnYXN5bmMgZGVmIGFzaygnLAogICAgJ2FzeW5jIGRlZiBxdWVyeSgnLApdCgpm')"
docker exec agora-backend-1 python -c "open('/tmp/b4patch.b64','a').write('bl9zdGFydCA9IC0xCmZvciBwYXQgaW4gY2hhdF9mbl9wYXR0ZXJuczoKICAgIGlkeCA9IGNvbnRlbnQuZmluZChwYXQpCiAgICBpZiBpZHggPj0gMDoKICAgICAgICBmbl9zdGFydCA9IGlkeAogICAgICAgIHByaW50KGYnRm91bmQgY2hh')"
docker exec agora-backend-1 python -c "open('/tmp/b4patch.b64','a').write('dCBmdW5jdGlvbiBhdCBpbmRleCB7aWR4fToge3BhdH0nKQogICAgICAgIGJyZWFrCgppZiBmbl9zdGFydCA8IDA6CiAgICAjIFRyeSB0byBmaW5kIGFueSBhc3luYyBkZWYgdGhhdCBoYW5kbGVzIHRoZSBtYWluIHJlcXVlc3QKICAgIG1h')"
docker exec agora-backend-1 python -c "open('/tmp/b4patch.b64','a').write('dGNoZXMgPSBsaXN0KHJlLmZpbmRpdGVyKHInYXN5bmMgZGVmIChcdyspXCgnLCBjb250ZW50KSkKICAgIGZvciBtIGluIG1hdGNoZXM6CiAgICAgICAgbmFtZSA9IG0uZ3JvdXAoMSkKICAgICAgICBpZiBuYW1lIG5vdCBpbiAoJ2xpZmVz')"
docker exec agora-backend-1 python -c "open('/tmp/b4patch.b64','a').write('cGFuJywgJ3Jvb3QnLCAnaGVhbHRoJyk6CiAgICAgICAgICAgIGZuX3N0YXJ0ID0gbS5zdGFydCgpCiAgICAgICAgICAgIHByaW50KGYnVXNpbmcgZnVuY3Rpb246IHtuYW1lfScpCiAgICAgICAgICAgIGJyZWFrCgojIOKUgOKUgCBTdGVw')"
docker exec agora-backend-1 python -c "open('/tmp/b4patch.b64','a').write('IDM6IEZpbmQgd2hlcmUgJ3N5c3RlbScgcHJvbXB0IGNvbnRlbnQgaXMgZGVmaW5lZCDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIAKIyBMb29rIGZvciBzeXN0ZW0gcHJvbXB0IHN0cmlu')"
docker exec agora-backend-1 python -c "open('/tmp/b4patch.b64','a').write('ZyBvciB2YXJpYWJsZQpzeXN0ZW1fcGF0dGVybnMgPSBbCiAgICAoJ3N5c3RlbV9wcm9tcHQgPSAnLCAndmFyaWFibGUnKSwKICAgICgnInN5c3RlbSI6ICcsICdkaWN0X2tleScpLAogICAgKCInc3lzdGVtJzogIiwgJ2RpY3Rfa2V5Jyks')"
docker exec agora-backend-1 python -c "open('/tmp/b4patch.b64','a').write('CiAgICAoJ3N5c3RlbV9jb250ZW50ID0gJywgJ3ZhcmlhYmxlJyksCiAgICAoJ2Jhc2Vfc3lzdGVtID0gJywgJ3ZhcmlhYmxlJyksCl0KCnN5c3RlbV9mb3VuZCA9IEZhbHNlCmZvciBwYXR0ZXJuLCBraW5kIGluIHN5c3RlbV9wYXR0ZXJu')"
docker exec agora-backend-1 python -c "open('/tmp/b4patch.b64','a').write('czoKICAgIGlkeCA9IGNvbnRlbnQuZmluZChwYXR0ZXJuKQogICAgaWYgaWR4ID49IDA6CiAgICAgICAgcHJpbnQoZidGb3VuZCBzeXN0ZW0gcHJvbXB0IHBhdHRlcm46IHtyZXByKHBhdHRlcm4pfSBhdCB7aWR4fScpCiAgICAgICAgc3lz')"
docker exec agora-backend-1 python -c "open('/tmp/b4patch.b64','a').write('dGVtX2ZvdW5kID0gVHJ1ZQogICAgICAgIGJyZWFrCgojIOKUgOKUgCBTdGVwIDQ6IEZpbmQgd2hlcmUgdGhlIEFudGhyb3BpYyBBUEkgaXMgY2FsbGVkIOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKU')"
docker exec agora-backend-1 python -c "open('/tmp/b4patch.b64','a').write('gOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgAojIExvb2sgZm9yIGh0dHB4IGNhbGwgb3IgYW50aHJvcGljIGNsaWVudCBjYWxsCmFwaV9jYWxsX3BhdHRlcm5zID0gWwogICAgJ2h0dHB4LkFzeW5jQ2xpZW50JywKICAgICdjbGllbnQu')"
docker exec agora-backend-1 python -c "open('/tmp/b4patch.b64','a').write('bWVzc2FnZXMuY3JlYXRlJywKICAgICdhbnRocm9waWMuQW50aHJvcGljJywKICAgICdhc3luY19hbnRocm9waWMnLAogICAgJ2F3YWl0IGNsaWVudC5wb3N0JywKXQoKYXBpX2NhbGxfaWR4ID0gLTEKZm9yIHBhdCBpbiBhcGlfY2FsbF9w')"
docker exec agora-backend-1 python -c "open('/tmp/b4patch.b64','a').write('YXR0ZXJuczoKICAgIGlkeCA9IGNvbnRlbnQuZmluZChwYXQpCiAgICBpZiBpZHggPj0gMDoKICAgICAgICBhcGlfY2FsbF9pZHggPSBpZHgKICAgICAgICBwcmludChmJ0ZvdW5kIEFQSSBjYWxsIGF0IHtpZHh9OiB7cGF0fScpCiAgICAg')"
docker exec agora-backend-1 python -c "open('/tmp/b4patch.b64','a').write('ICAgYnJlYWsKCiMg4pSA4pSAIFN0ZXAgNTogRmluZCByZXR1cm4gc3RhdGVtZW50IHdpdGggdGhlIHJlcGx5IOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKU')"
docker exec agora-backend-1 python -c "open('/tmp/b4patch.b64','a').write('gOKUgOKUgOKUgAojIExvb2sgZm9yIHdoZXJlIHRoZSByZXNwb25zZSBpcyByZXR1cm5lZApyZXR1cm5fcGF0dGVybnMgPSBbCiAgICAncmV0dXJuIHsicmVwbHkiJywKICAgICdyZXR1cm4geyJyZXNwb25zZSInLAogICAgJ3JldHVybiBK')"
docker exec agora-backend-1 python -c "open('/tmp/b4patch.b64','a').write('U09OUmVzcG9uc2UnLAogICAgJyJyZXBseSI6IHJlcGx5JywKICAgICcicmVzcG9uc2UiOiByZXNwb25zZScsCl0KCnJldHVybl9pZHggPSAtMQpyZXR1cm5fcGF0dGVybl9mb3VuZCA9IE5vbmUKZm9yIHBhdCBpbiByZXR1cm5fcGF0dGVy')"
docker exec agora-backend-1 python -c "open('/tmp/b4patch.b64','a').write('bnM6CiAgICBpZHggPSBjb250ZW50LnJmaW5kKHBhdCkKICAgIGlmIGlkeCA+PSAwOgogICAgICAgIHJldHVybl9pZHggPSBpZHgKICAgICAgICByZXR1cm5fcGF0dGVybl9mb3VuZCA9IHBhdAogICAgICAgIHByaW50KGYnRm91bmQgcmV0')"
docker exec agora-backend-1 python -c "open('/tmp/b4patch.b64','a').write('dXJuIGF0IHtpZHh9OiB7cGF0fScpCiAgICAgICAgYnJlYWsKCiMg4pSA4pSAIFN0ZXAgNjogSW5qZWN0IG1lbW9yeSBlbnJpY2htZW50IGJlZm9yZSBBUEkgY2FsbCDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDi')"
docker exec agora-backend-1 python -c "open('/tmp/b4patch.b64','a').write('lIDilIDilIDilIDilIDilIDilIDilIDilIDilIAKaWYgYXBpX2NhbGxfaWR4ID49IDA6CiAgICAjIEZpbmQgdGhlIHN0YXJ0IG9mIHRoZSBsaW5lIGNvbnRhaW5pbmcgdGhlIEFQSSBjYWxsCiAgICBsaW5lX3N0YXJ0ID0gY29udGVudC5y')"
docker exec agora-backend-1 python -c "open('/tmp/b4patch.b64','a').write('ZmluZCgnXG4nLCAwLCBhcGlfY2FsbF9pZHgpICsgMQogICAgaW5kZW50ID0gJycKICAgIGZvciBjaCBpbiBjb250ZW50W2xpbmVfc3RhcnQ6XToKICAgICAgICBpZiBjaCBpbiAoJyAnLCAnXHQnKToKICAgICAgICAgICAgaW5kZW50ICs9')"
docker exec agora-backend-1 python -c "open('/tmp/b4patch.b64','a').write('IGNoCiAgICAgICAgZWxzZToKICAgICAgICAgICAgYnJlYWsKCiAgICBtZW1vcnlfaW5qZWN0aW9uID0gZiIiIgp7aW5kZW50fSMgUGhhc2UgQzogRW5yaWNoIHdpdGggb3JnYW5pc2F0aW9uYWwgbWVtb3J5CntpbmRlbnR9aWYgUEhBU0Vf')"
docker exec agora-backend-1 python -c "open('/tmp/b4patch.b64','a').write('Q19FTkFCTEVEOgp7aW5kZW50fSAgICB0cnk6CntpbmRlbnR9ICAgICAgICBpbXBvcnQgdXVpZCBhcyBfdXVpZAp7aW5kZW50fSAgICAgICAgX3Nlc3Npb25faWQgPSBzdHIoX3V1aWQudXVpZDQoKSkKe2luZGVudH0gICAgICAgIF91c2Vy')"
docker exec agora-backend-1 python -c "open('/tmp/b4patch.b64','a').write('X3F1ZXJ5ID0gbWVzc2FnZSBpZiBpc2luc3RhbmNlKG1lc3NhZ2UsIHN0cikgZWxzZSBzdHIobWVzc2FnZSlbOjUwMF0Ke2luZGVudH0gICAgICAgIF91c2VyX2lkID0gc3RyKGN1cnJlbnRfdXNlci5pZCkgaWYgaGFzYXR0cihjdXJyZW50')"
docker exec agora-backend-1 python -c "open('/tmp/b4patch.b64','a').write('X3VzZXIsICdpZCcpIGVsc2Ugc3RyKGN1cnJlbnRfdXNlci5nZXQoJ2lkJywgJ3Vua25vd24nKSkKe2luZGVudH0gICAgICAgICMgU2VhcmNoIG1lbW9yeSBhbmQgYnVpbGQgZW5yaWNoZWQgY29udGV4dAp7aW5kZW50fSAgICAgICAgX21l')"
docker exec agora-backend-1 python -c "open('/tmp/b4patch.b64','a').write('bV9wcm9tcHQsIF9tZW1faWRzID0gYnVpbGRfbWVtb3J5X2F3YXJlX3N5c3RlbV9wcm9tcHQoCntpbmRlbnR9ICAgICAgICAgICAgZGI9ZGIsCntpbmRlbnR9ICAgICAgICAgICAgYmFzZV9zeXN0ZW1fcHJvbXB0PXN5c3RlbV9wcm9tcHQg')"
docker exec agora-backend-1 python -c "open('/tmp/b4patch.b64','a').write('aWYgJ3N5c3RlbV9wcm9tcHQnIGluIGRpcigpIGVsc2UgJycsCntpbmRlbnR9ICAgICAgICAgICAgdXNlcl9xdWVyeT1fdXNlcl9xdWVyeSwKe2luZGVudH0gICAgICAgICkKe2luZGVudH0gICAgICAgIGlmIF9tZW1fcHJvbXB0IGFuZCAn')"
docker exec agora-backend-1 python -c "open('/tmp/b4patch.b64','a').write('c3lzdGVtX3Byb21wdCcgaW4gZGlyKCk6CntpbmRlbnR9ICAgICAgICAgICAgc3lzdGVtX3Byb21wdCA9IF9tZW1fcHJvbXB0CntpbmRlbnR9ICAgICAgICAjIEVtaXQgY29uc3VsdGF0aW9uIGV2ZW50CntpbmRlbnR9ICAgICAgICBlbWl0')"
docker exec agora-backend-1 python -c "open('/tmp/b4patch.b64','a').write('X2NvcGlsb3RfY29uc3VsdGVkKAp7aW5kZW50fSAgICAgICAgICAgIGRiPWRiLAp7aW5kZW50fSAgICAgICAgICAgIHVzZXJfaWQ9X3VzZXJfaWQsCntpbmRlbnR9ICAgICAgICAgICAgc2Vzc2lvbl9pZD1fc2Vzc2lvbl9pZCwKe2luZGVu')"
docker exec agora-backend-1 python -c "open('/tmp/b4patch.b64','a').write('dH0gICAgICAgICAgICBxdWVyeV9zdW1tYXJ5PV91c2VyX3F1ZXJ5WzozMDBdLAp7aW5kZW50fSAgICAgICAgICAgIG1lbW9yeV9pdGVtc19jaXRlZD1fbWVtX2lkcywKe2luZGVudH0gICAgICAgICkKe2luZGVudH0gICAgICAgIGRiLmNv')"
docker exec agora-backend-1 python -c "open('/tmp/b4patch.b64','a').write('bW1pdCgpCntpbmRlbnR9ICAgIGV4Y2VwdCBFeGNlcHRpb24gYXMgX3BjX21lbV9lcnI6CntpbmRlbnR9ICAgICAgICBwYXNzICAjIE1lbW9yeSBlbnJpY2htZW50IGZhaWx1cmUgbmV2ZXIgYmxvY2tzIGNvcGlsb3QKCiIiIgogICAgY29u')"
docker exec agora-backend-1 python -c "open('/tmp/b4patch.b64','a').write('dGVudCA9IGNvbnRlbnRbOmxpbmVfc3RhcnRdICsgbWVtb3J5X2luamVjdGlvbiArIGNvbnRlbnRbbGluZV9zdGFydDpdCiAgICBwcmludCgnSW5qZWN0ZWQgbWVtb3J5IGVucmljaG1lbnQgYmVmb3JlIEFQSSBjYWxsJykKICAgIGFwaV9j')"
docker exec agora-backend-1 python -c "open('/tmp/b4patch.b64','a').write('YWxsX2lkeCArPSBsZW4obWVtb3J5X2luamVjdGlvbikKICAgIGlmIHJldHVybl9pZHggPj0gMDoKICAgICAgICByZXR1cm5faWR4ICs9IGxlbihtZW1vcnlfaW5qZWN0aW9uKQoKIyDilIDilIAgU3RlcCA3OiBJbmplY3QgcmVjb21tZW5k')"
docker exec agora-backend-1 python -c "open('/tmp/b4patch.b64','a').write('YXRpb24gcmVnaXN0cmF0aW9uIGJlZm9yZSByZXR1cm4g4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSACmlmIHJldHVybl9pZHggPj0gMCBhbmQgcmV0dXJuX3BhdHRlcm5fZm91bmQ6CiAgICBsaW5lX3N0')"
docker exec agora-backend-1 python -c "open('/tmp/b4patch.b64','a').write('YXJ0ID0gY29udGVudC5yZmluZCgnXG4nLCAwLCByZXR1cm5faWR4KSArIDEKICAgIGluZGVudCA9ICcnCiAgICBmb3IgY2ggaW4gY29udGVudFtsaW5lX3N0YXJ0Ol06CiAgICAgICAgaWYgY2ggaW4gKCcgJywgJ1x0Jyk6CiAgICAgICAg')"
docker exec agora-backend-1 python -c "open('/tmp/b4patch.b64','a').write('ICAgIGluZGVudCArPSBjaAogICAgICAgIGVsc2U6CiAgICAgICAgICAgIGJyZWFrCgogICAgcmVjX2luamVjdGlvbiA9IGYiIiIKe2luZGVudH0jIFBoYXNlIEM6IEF1dG8tcmVnaXN0ZXIgcmVjb21tZW5kYXRpb25zIGZyb20gcmVzcG9u')"
docker exec agora-backend-1 python -c "open('/tmp/b4patch.b64','a').write('c2UKe2luZGVudH1pZiBQSEFTRV9DX0VOQUJMRUQ6CntpbmRlbnR9ICAgIHRyeToKe2luZGVudH0gICAgICAgIF9yZXBseV90ZXh0ID0gcmVwbHkgaWYgJ3JlcGx5JyBpbiBkaXIoKSBlbHNlIHJlc3BvbnNlIGlmICdyZXNwb25zZScgaW4g')"
docker exec agora-backend-1 python -c "open('/tmp/b4patch.b64','a').write('ZGlyKCkgZWxzZSAnJwp7aW5kZW50fSAgICAgICAgaWYgX3JlcGx5X3RleHQgYW5kIGxlbihzdHIoX3JlcGx5X3RleHQpKSA+IDUwOgp7aW5kZW50fSAgICAgICAgICAgIF9jdHggPSB7eydkYXNoYm9hcmQnOiAnY29waWxvdCcsICd1c2Vy')"
docker exec agora-backend-1 python -c "open('/tmp/b4patch.b64','a').write('X2lkJzogX3VzZXJfaWQgaWYgJ191c2VyX2lkJyBpbiBkaXIoKSBlbHNlICd1bmtub3duJ319CntpbmRlbnR9ICAgICAgICAgICAgcmVnaXN0ZXJfcmVjb21tZW5kYXRpb25fZnJvbV9jb3BpbG90KAp7aW5kZW50fSAgICAgICAgICAgICAg')"
docker exec agora-backend-1 python -c "open('/tmp/b4patch.b64','a').write('ICBkYj1kYiwKe2luZGVudH0gICAgICAgICAgICAgICAgcmVzcG9uc2VfdGV4dD1zdHIoX3JlcGx5X3RleHQpLAp7aW5kZW50fSAgICAgICAgICAgICAgICB1c2VyX2lkPV91c2VyX2lkIGlmICdfdXNlcl9pZCcgaW4gZGlyKCkgZWxzZSBO')"
docker exec agora-backend-1 python -c "open('/tmp/b4patch.b64','a').write('b25lLAp7aW5kZW50fSAgICAgICAgICAgICAgICBjb250ZXh0X3NuYXBzaG90PV9jdHgsCntpbmRlbnR9ICAgICAgICAgICAgICAgIHNvdXJjZV9kYXNoYm9hcmQ9J2NvcGlsb3QnLAp7aW5kZW50fSAgICAgICAgICAgICAgICBjb25maWRl')"
docker exec agora-backend-1 python -c "open('/tmp/b4patch.b64','a').write('bmNlPTAuNjUsCntpbmRlbnR9ICAgICAgICAgICAgKQp7aW5kZW50fSAgICBleGNlcHQgRXhjZXB0aW9uIGFzIF9wY19yZWNfZXJyOgp7aW5kZW50fSAgICAgICAgcGFzcyAgIyBSZWdpc3RyYXRpb24gZmFpbHVyZSBuZXZlciBibG9ja3Mg')"
docker exec agora-backend-1 python -c "open('/tmp/b4patch.b64','a').write('cmVzcG9uc2UKCiIiIgogICAgY29udGVudCA9IGNvbnRlbnRbOmxpbmVfc3RhcnRdICsgcmVjX2luamVjdGlvbiArIGNvbnRlbnRbbGluZV9zdGFydDpdCiAgICBwcmludCgnSW5qZWN0ZWQgcmVjb21tZW5kYXRpb24gcmVnaXN0cmF0aW9u')"
docker exec agora-backend-1 python -c "open('/tmp/b4patch.b64','a').write('IGJlZm9yZSByZXR1cm4nKQoKIyDilIDilIAgU2F2ZSDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDi')"
docker exec agora-backend-1 python -c "open('/tmp/b4patch.b64','a').write('lIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIAKd2l0aCBvcGVuKHBhdGgsICd3JykgYXMgZjoKICAgIGYud3Jp')"
docker exec agora-backend-1 python -c "open('/tmp/b4patch.b64','a').write('dGUoY29udGVudCkKCiMgVmVyaWZ5CndpdGggb3BlbihwYXRoKSBhcyBmOgogICAgdmVyaWZ5ID0gZi5yZWFkKCkKcHJpbnQoZidTYXZlZCB7bGVuKHZlcmlmeSk6LH0gY2hhcnMnKQpwcmludChmJ1BIQVNFX0NfTUVNT1JZIHByZXNlbnQ6')"
docker exec agora-backend-1 python -c "open('/tmp/b4patch.b64','a').write('IHsiUEhBU0VfQ19NRU1PUlkiIGluIHZlcmlmeX0nKQpwcmludChmJ2J1aWxkX21lbW9yeV9hd2FyZV9zeXN0ZW1fcHJvbXB0IHByZXNlbnQ6IHsiYnVpbGRfbWVtb3J5X2F3YXJlX3N5c3RlbV9wcm9tcHQiIGluIHZlcmlmeX0nKQpwcmlu')"
docker exec agora-backend-1 python -c "open('/tmp/b4patch.b64','a').write('dChmJ3JlZ2lzdGVyX3JlY29tbWVuZGF0aW9uX2Zyb21fY29waWxvdCBwcmVzZW50OiB7InJlZ2lzdGVyX3JlY29tbWVuZGF0aW9uX2Zyb21fY29waWxvdCIgaW4gdmVyaWZ5fScpCnByaW50KCkKcHJpbnQoJ1BoYXNlIEMgQmF0Y2ggNCDi')"
docker exec agora-backend-1 python -c "open('/tmp/b4patch.b64','a').write('gJQgY29waWxvdF92OC5weSBwYXRjaGVkIHN1Y2Nlc3NmdWxseScpCnByaW50KCdUaGUgQ29waWxvdCBub3c6JykKcHJpbnQoJyAgMS4gU2VhcmNoZXMgb3JnYW5pc2F0aW9uYWwgbWVtb3J5IGJlZm9yZSBldmVyeSByZXNwb25zZScpCnBy')"
docker exec agora-backend-1 python -c "open('/tmp/b4patch.b64','a').write('aW50KCcgIDIuIEluamVjdHMgcmVsZXZhbnQgbWVtb3J5IGludG8gc3lzdGVtIHByb21wdCcpCnByaW50KCcgIDMuIEF1dG8tcmVnaXN0ZXJzIHJlY29tbWVuZGF0aW9ucyBmcm9tIHJlc3BvbnNlcycpCnByaW50KCcgIDQuIFRyYWNrcyBj')"
docker exec agora-backend-1 python -c "open('/tmp/b4patch.b64','a').write('b25zdWx0YXRpb25zIGluIHBsYXRmb3JtX2V2ZW50cycpCg==')"
docker exec agora-backend-1 python -c "import base64;open('/tmp/batch4_patch.py','w').write(base64.b64decode(open('/tmp/b4patch.b64').read()).decode())"
echo   OK script written
echo.
echo Step 2: Running patch...
docker exec agora-backend-1 python /tmp/batch4_patch.py
echo.
echo Step 3: Copying patched copilot to Windows source...
docker cp agora-backend-1:/app/app/api/routes/copilot_v8.py backend\app\api\routes\copilot_v8.py
echo.
echo Step 4: Verifying memory search works...
docker exec agora-backend-1 python -c "import sys;sys.path.insert(0,'/app');from app.phase_c.services.copilot_memory import get_memory_context;from app.db.database import SessionLocal;db=SessionLocal();result=get_memory_context(db,'stakeholder engagement diaspora');print('Memory context:',len(result),'chars');print(result[:200] if result else 'No memory found');db.close()"
echo.
echo Step 5: Running end-to-end memory-aware copilot test...
docker exec agora-backend-1 python -c "open('/tmp/b4test.b64','w').write('')"
docker exec agora-backend-1 python -c "open('/tmp/b4test.b64','a').write('aW1wb3J0IHN5cywgcmVxdWVzdHMKc3lzLnBhdGguaW5zZXJ0KDAsICcvYXBwJykKciA9IHJlcXVlc3RzLnBvc3QoJ2h0dHA6Ly9sb2NhbGhvc3Q6ODAwMC9hdXRoL2xvZ2luJywganNvbj17J2VtYWlsJzogJ2FkbWluQGFnb3JhLnJ0aWZu')"
docker exec agora-backend-1 python -c "open('/tmp/b4test.b64','a').write('Lm9yZycsICdwYXNzd29yZCc6ICdBZ29yYTIwMjQnfSkKaWYgci5zdGF0dXNfY29kZSAhPSAyMDA6CiAgICBwcmludCgnTG9naW4gZmFpbGVkIC0gcnVuIHBhc3N3b3JkIHJlc2V0JykKICAgIHN5cy5leGl0KDApCnRvayA9IHIuanNvbigp')"
docker exec agora-backend-1 python -c "open('/tmp/b4test.b64','a').write('WydhY2Nlc3NfdG9rZW4nXQpoID0geydBdXRob3JpemF0aW9uJzogZidCZWFyZXIge3Rva30nLCAnQ29udGVudC1UeXBlJzogJ2FwcGxpY2F0aW9uL2pzb24nfQoKIyBUZXN0IG1lbW9yeSByZXRyaWV2YWwKZnJvbSBhcHAuZGIuZGF0YWJh')"
docker exec agora-backend-1 python -c "open('/tmp/b4test.b64','a').write('c2UgaW1wb3J0IFNlc3Npb25Mb2NhbApmcm9tIGFwcC5waGFzZV9jLnNlcnZpY2VzLmNvcGlsb3RfbWVtb3J5IGltcG9ydCBnZXRfbWVtb3J5X2NvbnRleHQKZGIgPSBTZXNzaW9uTG9jYWwoKQptZW0gPSBnZXRfbWVtb3J5X2NvbnRleHQo')"
docker exec agora-backend-1 python -c "open('/tmp/b4test.b64','a').write('ZGIsICdzdGFrZWhvbGRlciBlbmdhZ2VtZW50JykKcHJpbnQoZidNZW1vcnkgY29udGV4dCByZXRyaWV2ZWQ6IHtsZW4obWVtKX0gY2hhcnMnKQppZiBtZW06CiAgICBwcmludCgnICBGaXJzdCAxNTAgY2hhcnM6JywgbWVtWzoxNTBdKQpk')"
docker exec agora-backend-1 python -c "open('/tmp/b4test.b64','a').write('Yi5jbG9zZSgpCgojIENoZWNrIHBsYXRmb3JtIGV2ZW50cyBmcm9tIGNvcGlsb3QKZnJvbSBzcWxhbGNoZW15IGltcG9ydCB0ZXh0CmRiMiA9IFNlc3Npb25Mb2NhbCgpCmV2ZW50cyA9IGRiMi5leGVjdXRlKHRleHQoIlNFTEVDVCBDT1VO')"
docker exec agora-backend-1 python -c "open('/tmp/b4test.b64','a').write('VCgqKSBGUk9NIHBsYXRmb3JtX2V2ZW50cyBXSEVSRSBldmVudF90eXBlPSdDb3BpbG90Q29uc3VsdGVkJyIpKS5zY2FsYXIoKQpyZWNzID0gZGIyLmV4ZWN1dGUodGV4dCgiU0VMRUNUIENPVU5UKCopIEZST00gcmVjb21tZW5kYXRpb25z')"
docker exec agora-backend-1 python -c "open('/tmp/b4test.b64','a').write('IFdIRVJFIHNvdXJjZV9kYXNoYm9hcmQ9J2NvcGlsb3QnIikpLnNjYWxhcigpCm1lbV9pdGVtcyA9IGRiMi5leGVjdXRlKHRleHQoIlNFTEVDVCBDT1VOVCgqKSBGUk9NIG9yZ2FuaXNhdGlvbmFsX21lbW9yeSBXSEVSRSB2YWxpZGF0aW9u')"
docker exec agora-backend-1 python -c "open('/tmp/b4test.b64','a').write('X3N0YXR1cz0ndmFsaWRhdGVkJyIpKS5zY2FsYXIoKQpwcmludChmJ1BsYXRmb3JtIGV2ZW50cyAoQ29waWxvdENvbnN1bHRlZCk6IHtldmVudHN9JykKcHJpbnQoZidSZWNvbW1lbmRhdGlvbnMgZnJvbSBDb3BpbG90OiB7cmVjc30nKQpw')"
docker exec agora-backend-1 python -c "open('/tmp/b4test.b64','a').write('cmludChmJ1ZhbGlkYXRlZCBtZW1vcnkgaXRlbXM6IHttZW1faXRlbXN9JykKZGIyLmNsb3NlKCkKcHJpbnQoKQpwcmludCgnUGhhc2UgQyBCYXRjaCA0IHZlcmlmaWNhdGlvbiBjb21wbGV0ZScpCg==')"
docker exec agora-backend-1 python -c "import base64;open('/tmp/batch4_test.py','w').write(base64.b64decode(open('/tmp/b4test.b64').read()).decode())"
docker exec agora-backend-1 python /tmp/batch4_test.py
echo.
echo ============================================================
echo Phase C Batch 4 complete.
echo The Copilot now searches organisational memory before every
echo response and auto-registers recommendations.
echo ============================================================
pause