"""
Phase D.2 — Members Foundation: Chapter model.

New file (per D.2 directive — models/chapter.py, models/member.py,
models/member_profile.py, models/member_session.py, rather than being
appended to models.py as Phase D.1's geography models were). No existing
model file is modified.

UUID primary key generated by native PostgreSQL gen_random_uuid() (built
into Postgres core since v13 — no extension required; verified against a
disposable Postgres 16.2 instance matching production before deployment).

created_at / updated_at carry a database-level server_default in addition
to the ORM-side default, applying the lesson learned in Phase D.1 (a
migration's raw INSERTs failed a NOT NULL check because the ORM-created
table lacked a DB-level default for created_at). This module has no raw
seed INSERTs for `members`/`member_profiles`/`member_sessions`, but
`chapters` does (see migrations/phase_d_02_members.sql), so this
protection is applied consistently across every table in this module.
"""
import uuid
from datetime import datetime
from typing import Optional, TYPE_CHECKING

from sqlalchemy import String, Boolean, DateTime, ForeignKey, Index, text
from sqlalchemy.dialects.postgresql import UUID as PG_UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.database import Base
from app.models.models import utcnow

if TYPE_CHECKING:
    from app.models.member import Member


class Chapter(Base):
    __tablename__ = "chapters"

    id: Mapped[uuid.UUID] = mapped_column(
        PG_UUID(as_uuid=True), primary_key=True, server_default=text("gen_random_uuid()")
    )
    name: Mapped[str] = mapped_column(String(255), nullable=False)
    country: Mapped[str] = mapped_column(String(100), nullable=False)
    state_id: Mapped[Optional[int]] = mapped_column(ForeignKey("ng_states.id"))
    city: Mapped[Optional[str]] = mapped_column(String(150))
    chapter_type: Mapped[str] = mapped_column(String(50), nullable=False, default="local")
    chairperson: Mapped[Optional[str]] = mapped_column(String(255))
    email: Mapped[Optional[str]] = mapped_column(String(255))
    phone: Mapped[Optional[str]] = mapped_column(String(50))
    status: Mapped[str] = mapped_column(String(20), nullable=False, default="active")
    is_active: Mapped[bool] = mapped_column(Boolean, nullable=False, default=True)

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=text("now()"), default=utcnow
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=text("now()"), default=utcnow, onupdate=utcnow
    )
    deleted_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True))

    members: Mapped[list["Member"]] = relationship(back_populates="chapter")

    __table_args__ = (
        Index("ux_chapters_name_live", "name", unique=True, postgresql_where=text("deleted_at IS NULL")),
        Index("ix_chapters_country", "country"),
        Index("ix_chapters_state_id", "state_id"),
        Index("ix_chapters_status", "status"),
    )
