#!/usr/bin/env python3
"""
NDIP V5.6 — One-time cleanup of pre-fix test/diagnostic recommendations.

During the dead-code bug diagnosis on 17 June 2026, several manual test calls
to record_recommendation() were made directly (bypassing the real Decision
Support pipeline) to isolate the bug. These created noise records that would
dilute the V5.6 Decision Quality Metrics once real evaluation begins.

This script removes only the identifiable test records, leaving genuine
recommendations generated by the real generate_decision_support() pipeline
(both before and after the fix) intact, since those reflect real platform
behaviour and are valid data points.

Run: docker exec agora-backend-1 python scripts/cleanup_test_recommendations.py
"""
import sys
sys.path.insert(0, '/app')

from app.db.database import SessionLocal
from app.models.models import RecommendationRecord

# Exact text fragments used only in manual diagnostic test calls during this session.
# Matching narrowly on purpose — we want to remove ONLY known test noise,
# never accidentally delete genuine recommendations.
TEST_MARKERS = [
    "Test recommendation",
    "test action",
    "test evidence",
    "test outcome",
]


def main():
    db = SessionLocal()
    try:
        all_recs = db.query(RecommendationRecord).all()
        total = len(all_recs)

        to_delete = []
        for rec in all_recs:
            text_fields = " ".join(filter(None, [
                rec.recommendation_text,
                rec.supporting_evidence,
                rec.expected_outcome,
            ]))
            if any(marker in text_fields for marker in TEST_MARKERS):
                to_delete.append(rec)

        print("=" * 60)
        print("  NDIP V5.6 — Test Recommendation Cleanup")
        print("=" * 60)
        print(f"\n  Total recommendations in database: {total}")
        print(f"  Identified as test/diagnostic noise: {len(to_delete)}")

        if to_delete:
            print("\n  Records to be removed:")
            for rec in to_delete:
                print(f"    ID {rec.id} | {rec.recommendation_category} | {rec.recommendation_text[:60]}")

            for rec in to_delete:
                db.delete(rec)
            db.commit()
            print(f"\n  Deleted {len(to_delete)} test record(s).")
        else:
            print("\n  No test records found — database is already clean.")

        remaining = db.query(RecommendationRecord).count()
        print(f"\n  Remaining genuine recommendations: {remaining}")
        print("\n" + "=" * 60)
        print("  Cleanup complete")
        print("=" * 60)

    finally:
        db.close()


if __name__ == "__main__":
    main()
