"""
NDIP Recommendation Effectiveness Tracker v5.6
Tracks every recommendation generated by the Decision Support Engine,
automatically evaluates effectiveness against actual discourse outcomes,
and computes platform-wide decision quality metrics.

This is the V5.6 "Learning Decision Support" layer:
Generate → Track → Evaluate → Learn → Report.
"""
from datetime import datetime, timezone, timedelta
from typing import Optional
from sqlalchemy.orm import Session
from sqlalchemy import desc

from app.models.models import RecommendationRecord, RecommendationStatus


# ─── Outcome scoring scale ─────────────────────────────────────────────────────
OUTCOME_SCORES = {
    "INCORRECT": 0,
    "WEAK": 25,
    "PARTIALLY_CORRECT": 50,
    "MOSTLY_CORRECT": 75,
    "FULLY_CORRECT": 100,
}

# Minimum age (days) before a recommendation is eligible for automated evaluation.
# Forecasts need time to play out before we can judge them fairly.
MIN_EVALUATION_AGE_DAYS = 7


def record_recommendation(
    db: Session,
    narrative: Optional[str],
    recommendation_text: str,
    category: str,
    priority: str = "Medium",
    confidence: str = "Medium",
    time_horizon: Optional[str] = None,
    supporting_evidence: Optional[str] = None,
    expected_outcome: Optional[str] = None,
    trigger_metric_name: Optional[str] = None,
    trigger_metric_value: Optional[float] = None,
    period_days: int = 7,
    module: str = "decision_support",
) -> RecommendationRecord:
    """
    Persist a single recommendation for later effectiveness evaluation.
    Called by any NDIP module each time it generates a trackable recommendation.

    module identifies which platform module generated the recommendation,
    e.g. "decision_support", "national_pulse", "situation_room", "leadership_pack",
    "election_intelligence", "gnei", "entity_intelligence", "watchlist".
    """
    # Defensive coercion: text-typed columns must receive strings. A caller
    # accidentally passing a dict/list (e.g. an outlook structure instead of
    # its text field) would otherwise crash the INSERT entirely, rolling back
    # the whole session. Coerce here so a caller bug degrades to imperfect
    # text rather than a hard failure.
    if not isinstance(recommendation_text, str):
        recommendation_text = str(recommendation_text)
    if supporting_evidence is not None and not isinstance(supporting_evidence, str):
        supporting_evidence = str(supporting_evidence)
    if expected_outcome is not None and not isinstance(expected_outcome, str):
        expected_outcome = str(expected_outcome)

    # Deduplication guard: if an OPEN, unevaluated recommendation with the
    # exact same module + category + narrative + text already exists and was
    # created within the last 24 hours, return it instead of inserting a
    # duplicate. Without this, repeated calls to the same module within a
    # short window (e.g. manual testing, retries, or a page being refreshed
    # multiple times) silently pile up identical OPEN rows, inflating the
    # "Generated" count without adding any genuine new signal.
    recent_cutoff = datetime.now(timezone.utc) - timedelta(hours=24)
    existing = db.query(RecommendationRecord).filter(
        RecommendationRecord.module == module,
        RecommendationRecord.recommendation_category == category,
        RecommendationRecord.narrative == narrative,
        RecommendationRecord.recommendation_text == recommendation_text,
        RecommendationRecord.status == RecommendationStatus.OPEN,
        RecommendationRecord.created_at >= recent_cutoff,
    ).order_by(desc(RecommendationRecord.created_at)).first()
    if existing:
        return existing

    rec = RecommendationRecord(
        module=module,
        narrative=narrative,
        recommendation_text=recommendation_text,
        recommendation_category=category,
        priority=priority,
        confidence=confidence,
        time_horizon=time_horizon,
        supporting_evidence=supporting_evidence,
        expected_outcome=expected_outcome,
        trigger_metric_name=trigger_metric_name,
        trigger_metric_value=trigger_metric_value,
        status=RecommendationStatus.OPEN,
        period_days=period_days,
    )
    db.add(rec)
    db.commit()
    db.refresh(rec)
    return rec


def record_recommendations_batch(db: Session, recommendations: list, period_days: int = 7, module: str = "decision_support") -> int:
    """
    Persist a batch of recommendations (e.g. from a single Decision Support run).
    Each item should be a dict matching the recommendation structure.
    Returns count of recommendations recorded.
    """
    count = 0
    for r in recommendations:
        try:
            record_recommendation(
                db,
                narrative=r.get("narrative") or _infer_narrative(r.get("issue", "")),
                recommendation_text=r.get("action") or r.get("recommended_action", ""),
                category=r.get("category", "MONITOR"),
                priority=r.get("priority", "Medium"),
                confidence=r.get("confidence", "Medium"),
                time_horizon=r.get("time_horizon"),
                supporting_evidence=r.get("evidence") or r.get("reasoning"),
                expected_outcome=r.get("expected_outcome"),
                trigger_metric_name=r.get("trigger_metric_name"),
                trigger_metric_value=r.get("trigger_metric_value"),
                period_days=period_days,
                module=r.get("module", module),
            )
            count += 1
        except Exception:
            continue
    return count


def _infer_narrative(text: str) -> Optional[str]:
    """Best-effort narrative inference from issue/action text for tagging purposes."""
    text_lower = text.lower()
    mapping = {
        "governance": "Governance",
        "security": "Security",
        "election": "Elections & Democracy",
        "electoral": "Elections & Democracy",
        "economy": "Economy",
        "economic": "Economy",
        "diaspora": "Global Nigerian Engagement",
        "global nigerian": "Global Nigerian Engagement",
        "investment": "Investment",
        "media": "Media Representation",
        "infrastructure": "Infrastructure",
        "energy": "Energy",
        "education": "Education",
        "health": "Health",
    }
    for key, narrative in mapping.items():
        if key in text_lower:
            return narrative
    return None


# ─── Automated Evaluation Engine (Phase C) ────────────────────────────────────

def evaluate_recommendation_effectiveness(db: Session, rec: RecommendationRecord) -> dict:
    """
    Compare a recommendation's trigger condition against current discourse data
    to determine whether the recommendation was validated.

    Logic:
    - MONITOR/ESCALATE recommendations tied to a metric (e.g. "Security momentum")
      are validated if the metric continued in the predicted direction.
    - ACT/ENGAGE recommendations are evaluated against whether the underlying
      condition (e.g. peak engagement window) persisted or changed as expected.
    - INVESTIGATE/PREPARE recommendations are evaluated more leniently since they
      are process recommendations rather than directional forecasts.
    """
    from app.analytics.strategic_narratives import get_narrative_analysis

    if not rec.narrative:
        return _evaluate_generic(rec)

    # Get current narrative state to compare against the trigger snapshot
    current_narratives = get_narrative_analysis(db, rec.period_days)
    current = next((n for n in current_narratives if n["narrative"] == rec.narrative), None)

    if not current:
        return {
            "status": RecommendationStatus.UNDER_REVIEW,
            "outcome_score": None,
            "outcome_notes": f"Narrative '{rec.narrative}' not found in current analysis — cannot evaluate.",
            "outcome_metric_value": None,
        }

    category = rec.recommendation_category
    trigger_value = rec.trigger_metric_value
    trigger_metric = rec.trigger_metric_name or "share_of_voice"
    current_value = current.get(trigger_metric, current.get("share_of_voice", 0))

    # ── ESCALATE / MONITOR: directional forecast evaluation ──────────────────
    if category in ("ESCALATE", "MONITOR"):
        if trigger_value is None:
            return _evaluate_generic(rec)

        change = current_value - trigger_value
        change_pct = (change / abs(trigger_value) * 100) if trigger_value else 0

        # Recommendation predicted continued growth / escalation
        if change_pct > 15:
            return {
                "status": RecommendationStatus.VALIDATED,
                "outcome_score": OUTCOME_SCORES["FULLY_CORRECT"],
                "outcome_notes": (
                    f"{rec.narrative} {trigger_metric} continued rising from {trigger_value:.1f} "
                    f"to {current_value:.1f} ({change_pct:+.0f}%), confirming the {category.lower()} recommendation."
                ),
                "outcome_metric_value": current_value,
            }
        elif change_pct > 0:
            return {
                "status": RecommendationStatus.PARTIALLY_VALIDATED,
                "outcome_score": OUTCOME_SCORES["PARTIALLY_CORRECT"],
                "outcome_notes": (
                    f"{rec.narrative} {trigger_metric} rose modestly from {trigger_value:.1f} "
                    f"to {current_value:.1f} ({change_pct:+.0f}%) — directionally correct but weaker than flagged."
                ),
                "outcome_metric_value": current_value,
            }
        elif change_pct > -15:
            return {
                "status": RecommendationStatus.PARTIALLY_VALIDATED,
                "outcome_score": OUTCOME_SCORES["WEAK"],
                "outcome_notes": (
                    f"{rec.narrative} {trigger_metric} remained roughly flat ({trigger_value:.1f} → "
                    f"{current_value:.1f}, {change_pct:+.0f}%) — the predicted escalation did not clearly materialise."
                ),
                "outcome_metric_value": current_value,
            }
        else:
            return {
                "status": RecommendationStatus.INVALIDATED,
                "outcome_score": OUTCOME_SCORES["INCORRECT"],
                "outcome_notes": (
                    f"{rec.narrative} {trigger_metric} declined from {trigger_value:.1f} to "
                    f"{current_value:.1f} ({change_pct:+.0f}%) — the opposite of the predicted trend."
                ),
                "outcome_metric_value": current_value,
            }

    # ── ACT / ENGAGE: opportunity-window evaluation ───────────────────────────
    elif category in ("ACT", "ENGAGE"):
        sov_now = current.get("share_of_voice", 0)
        sentiment_now = current.get("sentiment_label", "neutral")

        if trigger_value and sov_now >= trigger_value * 0.7:
            return {
                "status": RecommendationStatus.VALIDATED,
                "outcome_score": OUTCOME_SCORES["MOSTLY_CORRECT"],
                "outcome_notes": (
                    f"{rec.narrative} maintained strong share of voice ({sov_now:.1f}% vs "
                    f"{trigger_value:.1f}% at recommendation time) — engagement window assessment was sound."
                ),
                "outcome_metric_value": sov_now,
            }
        elif trigger_value and sov_now >= trigger_value * 0.4:
            return {
                "status": RecommendationStatus.PARTIALLY_VALIDATED,
                "outcome_score": OUTCOME_SCORES["PARTIALLY_CORRECT"],
                "outcome_notes": (
                    f"{rec.narrative} share of voice declined from {trigger_value:.1f}% to {sov_now:.1f}% "
                    f"— the engagement window narrowed faster than the recommendation anticipated."
                ),
                "outcome_metric_value": sov_now,
            }
        else:
            return {
                "status": RecommendationStatus.PARTIALLY_VALIDATED,
                "outcome_score": OUTCOME_SCORES["WEAK"],
                "outcome_notes": (
                    f"{rec.narrative} attention has shifted substantially since the recommendation — "
                    f"current share of voice {sov_now:.1f}%. Window may have closed faster than expected."
                ),
                "outcome_metric_value": sov_now,
            }

    # ── INVESTIGATE / PREPARE: process recommendations, evaluated leniently ──
    else:
        return {
            "status": RecommendationStatus.VALIDATED,
            "outcome_score": OUTCOME_SCORES["MOSTLY_CORRECT"],
            "outcome_notes": (
                f"{category} recommendations are process-oriented rather than directional forecasts. "
                f"Marked as validated by default unless manually reviewed and overridden."
            ),
            "outcome_metric_value": current.get("share_of_voice", 0),
        }


def _evaluate_generic(rec: RecommendationRecord) -> dict:
    """Fallback evaluation when no narrative or trigger metric is available."""
    return {
        "status": RecommendationStatus.UNDER_REVIEW,
        "outcome_score": None,
        "outcome_notes": "Insufficient trigger metric data for automated evaluation. Requires manual review.",
        "outcome_metric_value": None,
    }


def run_evaluation_cycle(db: Session, max_records: int = 50) -> dict:
    """
    Find all OPEN recommendations old enough to evaluate, run automated evaluation,
    and update their records. This should be run periodically (e.g. daily via scheduler).
    """
    cutoff = datetime.now(timezone.utc) - timedelta(days=MIN_EVALUATION_AGE_DAYS)

    eligible = db.query(RecommendationRecord).filter(
        RecommendationRecord.status == RecommendationStatus.OPEN,
        RecommendationRecord.created_at <= cutoff,
    ).limit(max_records).all()

    evaluated = 0
    validated = 0
    partially_validated = 0
    invalidated = 0
    under_review = 0

    for rec in eligible:
        try:
            result = evaluate_recommendation_effectiveness(db, rec)
            rec.status = result["status"]
            rec.outcome_score = result["outcome_score"]
            rec.outcome_notes = result["outcome_notes"]
            rec.outcome_metric_value = result["outcome_metric_value"]
            rec.evaluation_date = datetime.now(timezone.utc)
            evaluated += 1

            if result["status"] == RecommendationStatus.VALIDATED:
                validated += 1
            elif result["status"] == RecommendationStatus.PARTIALLY_VALIDATED:
                partially_validated += 1
            elif result["status"] == RecommendationStatus.INVALIDATED:
                invalidated += 1
            else:
                under_review += 1
        except Exception:
            continue

    db.commit()

    return {
        "evaluated_this_cycle": evaluated,
        "validated": validated,
        "partially_validated": partially_validated,
        "invalidated": invalidated,
        "under_review": under_review,
        "eligible_found": len(eligible),
    }


# ─── Phase D: Decision Quality Metrics ────────────────────────────────────────

def compute_decision_quality_metrics(db: Session) -> dict:
    """
    Compute platform-wide decision support quality metrics across all
    evaluated recommendations.
    """
    all_recs = db.query(RecommendationRecord).all()
    total_generated = len(all_recs)

    evaluated = [r for r in all_recs if r.status != RecommendationStatus.OPEN]
    total_evaluated = len(evaluated)

    validated = [r for r in evaluated if r.status == RecommendationStatus.VALIDATED]
    partially_validated = [r for r in evaluated if r.status == RecommendationStatus.PARTIALLY_VALIDATED]
    invalidated = [r for r in evaluated if r.status == RecommendationStatus.INVALIDATED]
    under_review = [r for r in evaluated if r.status == RecommendationStatus.UNDER_REVIEW]

    scored = [r for r in evaluated if r.outcome_score is not None]
    avg_accuracy = round(sum(r.outcome_score for r in scored) / len(scored)) if scored else None

    # By category
    def category_accuracy(cat: str) -> Optional[int]:
        cat_recs = [r for r in scored if r.recommendation_category == cat]
        if not cat_recs:
            return None
        return round(sum(r.outcome_score for r in cat_recs) / len(cat_recs))

    action_success_rate = category_accuracy("ACT")
    monitoring_success_rate = category_accuracy("MONITOR")
    escalation_accuracy = category_accuracy("ESCALATE")
    engagement_accuracy = category_accuracy("ENGAGE")

    # Forecast accuracy = ESCALATE + MONITOR combined (directional predictions)
    forecast_recs = [r for r in scored if r.recommendation_category in ("ESCALATE", "MONITOR")]
    forecast_accuracy = round(sum(r.outcome_score for r in forecast_recs) / len(forecast_recs)) if forecast_recs else None

    # Narrative-level breakdown
    narrative_accuracy = {}
    for r in scored:
        if r.narrative:
            narrative_accuracy.setdefault(r.narrative, []).append(r.outcome_score)
    narrative_prediction_accuracy = {
        n: round(sum(scores) / len(scores)) for n, scores in narrative_accuracy.items()
    }

    # V5.8 Phase D — module-level accuracy breakdown (every module is self-evaluating)
    def module_accuracy(mod: str) -> Optional[int]:
        mod_recs = [r for r in scored if r.module == mod]
        if not mod_recs:
            return None
        return round(sum(r.outcome_score for r in mod_recs) / len(mod_recs))

    module_breakdown = {}
    for mod in set(r.module for r in all_recs if r.module):
        acc = module_accuracy(mod)
        mod_total = len([r for r in all_recs if r.module == mod])
        mod_evaluated = len([r for r in evaluated if r.module == mod])
        module_breakdown[mod] = {
            "generated": mod_total,
            "evaluated": mod_evaluated,
            "accuracy": acc,
        }

    # V5.8 Phase D — Outlook / Risk / Opportunity accuracy, sourced from sub-categories
    # within the PREPARE/INVESTIGATE space that specifically relate to outlook,
    # risk, or opportunity framing (tagged via supporting_evidence/recommendation_text
    # heuristics since these aren't a distinct category in the V5.6 schema).
    def text_tagged_accuracy(keyword: str) -> Optional[int]:
        tagged = [
            r for r in scored
            if (r.recommendation_text and keyword in r.recommendation_text.lower())
            or (r.supporting_evidence and keyword in r.supporting_evidence.lower())
        ]
        if not tagged:
            return None
        return round(sum(r.outcome_score for r in tagged) / len(tagged))

    outlook_accuracy = text_tagged_accuracy("outlook")
    risk_detection_accuracy = text_tagged_accuracy("risk")
    opportunity_detection_accuracy = text_tagged_accuracy("opportunity")

    # Platform Learning Score — a single composite figure combining the
    # available accuracy signals, weighted toward the metrics with more
    # evaluated volume so a single lucky/unlucky narrow metric can't dominate.
    component_scores = [
        (avg_accuracy, len(scored)),
        (forecast_accuracy, len(forecast_recs)),
        (action_success_rate, len([r for r in scored if r.recommendation_category == "ACT"])),
        (monitoring_success_rate, len([r for r in scored if r.recommendation_category == "MONITOR"])),
    ]
    weighted = [(score, weight) for score, weight in component_scores if score is not None and weight > 0]
    if weighted:
        total_weight = sum(w for _, w in weighted)
        platform_learning_score = round(sum(s * w for s, w in weighted) / total_weight)
    else:
        platform_learning_score = None

    return {
        "recommendations_generated": total_generated,
        "recommendations_evaluated": total_evaluated,
        "validated_count": len(validated),
        "partially_validated_count": len(partially_validated),
        "invalidated_count": len(invalidated),
        "under_review_count": len(under_review),
        "average_accuracy": avg_accuracy,
        "recommendation_accuracy": avg_accuracy,  # alias per spec
        "forecast_accuracy": forecast_accuracy,
        "action_success_rate": action_success_rate,
        "monitoring_success_rate": monitoring_success_rate,
        "escalation_accuracy": escalation_accuracy,
        "engagement_accuracy": engagement_accuracy,
        "narrative_prediction_accuracy": narrative_prediction_accuracy,
        "evaluation_rate": round(total_evaluated / total_generated * 100) if total_generated else 0,
        # V5.8 additions
        "module_breakdown": module_breakdown,
        "outlook_accuracy": outlook_accuracy,
        "risk_detection_accuracy": risk_detection_accuracy,
        "opportunity_detection_accuracy": opportunity_detection_accuracy,
        "platform_learning_score": platform_learning_score,
    }


def get_decision_support_performance_summary(db: Session) -> dict:
    """
    Phase E: Executive Learning Loop summary.
    Designed for direct display: Generated / Evaluated / Validated /
    Partially Validated / Invalidated / Average Accuracy.
    """
    metrics = compute_decision_quality_metrics(db)

    generated = metrics["recommendations_generated"]
    evaluated = metrics["recommendations_evaluated"]
    avg_acc = metrics["average_accuracy"]

    if generated == 0:
        narrative_summary = (
            "Decision Support Performance tracking has just been activated. "
            "No recommendations have been recorded yet — this summary will populate "
            "as the platform generates and evaluates recommendations over time."
        )
    elif evaluated == 0:
        narrative_summary = (
            f"{generated} recommendation(s) generated and currently being tracked. "
            f"None are old enough yet for automated evaluation (minimum {MIN_EVALUATION_AGE_DAYS} days). "
            f"Performance metrics will populate as recommendations mature."
        )
    else:
        validated_pct = round(metrics["validated_count"] / evaluated * 100) if evaluated else 0
        narrative_summary = (
            f"NDIP has generated {generated} recommendations, with {evaluated} evaluated against "
            f"actual discourse outcomes. {validated_pct}% were validated or partially validated, "
            f"with an average accuracy score of {avg_acc if avg_acc is not None else 'N/A'}%. "
            f"This demonstrates the platform's evolving decision-support reliability."
        )

    return {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "recommendations_generated": generated,
        "recommendations_evaluated": evaluated,
        "validated": metrics["validated_count"],
        "partially_validated": metrics["partially_validated_count"],
        "invalidated": metrics["invalidated_count"],
        "under_review": metrics["under_review_count"],
        "average_accuracy": avg_acc,
        "evaluation_rate": metrics["evaluation_rate"],
        "narrative_summary": narrative_summary,
        "metrics": metrics,
    }


def get_recent_recommendations(db: Session, limit: int = 20, status: Optional[str] = None) -> list:
    """Return recent recommendation records, optionally filtered by status, for review/display."""
    q = db.query(RecommendationRecord).order_by(desc(RecommendationRecord.created_at))
    if status:
        q = q.filter(RecommendationRecord.status == status)
    records = q.limit(limit).all()
    return [
        {
            "id": r.id,
            "created_at": r.created_at.isoformat() if r.created_at else None,
            "narrative": r.narrative,
            "recommendation_text": r.recommendation_text,
            "category": r.recommendation_category,
            "priority": r.priority,
            "confidence": r.confidence,
            "time_horizon": r.time_horizon,
            "status": r.status,
            "outcome_score": r.outcome_score,
            "outcome_notes": r.outcome_notes,
            "evaluation_date": r.evaluation_date.isoformat() if r.evaluation_date else None,
        }
        for r in records
    ]
